src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Once the boutique is allocated the preferred client advisor is defined considering both amount and recency of purchases, as above</inlineHelpText>
        <label>Allocated Client Advisor</label>
        <referenceTo>Associated__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Misure_Sartoriali__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Schede_Misura_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associate</label>
        <referenceTo>Associated__c</referenceTo>
        <relationshipLabel>Schede Misure Sartoria Solomeo</relationshipLabel>
        <relationshipName>Schede_Misure_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Circonferenza_torace__c</fullName>
        <label>Circonferenza torace</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circonferenza_vita_pantalone__c</fullName>
        <label>Circonferenza vita (pantalone)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ordine_Sartoria_Solomeo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordine Sartoria Solomeo</label>
        <referenceTo>Ordine_Sartoria_Solomeo__c</referenceTo>
        <relationshipLabel>Schede Misure Sartoria Solomeo</relationshipLabel>
        <relationshipName>Schede_Misure_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheda Misure Sartoria Solomeo</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Nome Scheda Misura Sartoria Solomeo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schede Misure Sartoria Solomeo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associated__c.object
<CustomObject>
    <description>Anagrafiche venditori negozi (collegato a Store di riferimento)</description>
    <fields>
        <fullName>Id_Associate_Micros__c</fullName>
        <label>Id Associate Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Associateds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Ordine_Sartoria_Solomeo__c.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associate</label>
        <referenceTo>Associated__c</referenceTo>
        <relationshipLabel>Ordini Sartoria Solomeo</relationshipLabel>
        <relationshipName>Ordini_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ordine Sartoria Solomeo</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Nome Ordine Sartoria Solomeo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordini Sartoria Solomeo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Codice_Boutique__c</fullName>
        <label>Codice Boutique</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Rest_MTM_MisureCustomerTest.cls
@isTest
public class Rest_MTM_MisureCustomerTest {

    @isTest static void test_Get(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        usr.Codice_Boutique__c = '001';
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
        
        Account acc = AllDataFactory.create_Account();
        insert acc;
        
        Account_Misure_Sartoriali__c ams  = AllDataFactory.create_Account_Misure_Sartoriali();
		ams.Account__c = acc.Id;
        insert ams;
		        
        req.requestURI =    '/MTM/V1/Misure/'+acc.Id; 
        req.httpMethod = 'GET';
        
        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = Rest_MTM_MisureCustomer.doGet();
        
        System.debug(rw);
            
            }
        Test.stopTest();
        
    }
    @isTest static void test_GetError(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
        
        Account acc = AllDataFactory.create_Account();
        insert acc;
        
        Account_Misure_Sartoriali__c ams  = AllDataFactory.create_Account_Misure_Sartoriali();
		ams.Account__c = acc.Id;
        insert ams;
		        
        req.requestURI =    '/MTM/V1/Misure/'+acc.Id; 
        req.httpMethod = 'GET';
        
        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = Rest_MTM_MisureCustomer.doGet();
        
        System.debug(rw);
        
            }
        Test.stopTest();
    }
    
    
     @isTest static void test_Post(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        usr.Codice_Boutique__c = '001';
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
        
        Account acc = AllDataFactory.create_Account();
        insert acc;
        //MC- To test order attachments process
        Location__c c = new Location__c();
        insert c;
               
        Associated__c t = new Associated__c();
        t.Id_Associate_Micros__c = '123456789';
        t.Location__c = c.Id;
        insert t;
        
        Ordine_Sartoria_Solomeo__c oss = new Ordine_Sartoria_Solomeo__c();
        oss.Associate__c = t.id;
        
        insert oss;
        string ossname = [SELECT Name FROM Ordine_Sartoria_Solomeo__c WHERE Id=:oss.Id].Name;
        //insert attachments order
        List<Attachment> aList = new List<Attachment>();
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'pdf_' + ossname + '.pdf', 'pdf'));
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'pdf_cliente_' + ossname + '.pdf', 'pdf'));
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'img_' + ossname + '.png', 'png'));
        insert aList;
        //MC-
         
        Account_Misure_Sartoriali__c ams  = AllDataFactory.create_Account_Misure_Sartoriali();
		ams.Account__c = acc.Id;
        ams.Ordine_Sartoria_Solomeo__c = oss.Id; 
        
		        
        req.requestURI =    '/MTM/V1/Misure/'; 
        req.httpMethod = 'Post';
        
        RestContext.response= res;
        RestContext.request = req;
         
       Rest_MTM_MisureCustomer.MisureWrapper mW = new Rest_MTM_MisureCustomer.MisureWrapper();
         mW.step = 'I';
         mW.data = ams;
         //MC- to test order attachments process
         List<Rest_MTM_MisureCustomer.AttachWrapper> awList = new List<Rest_MTM_MisureCustomer.AttachWrapper>();
         awList.add(ALLDataFactory.create_postAttachWrapper('pdf','pdf','testRest1'));
         awList.add(ALLDataFactory.create_postAttachWrapper('pdf','pdf_cliente','testRest1'));
         awList.add(ALLDataFactory.create_postAttachWrapper('png','img','testRest1'));
         mW.attachments = awList;
        
        ResponseWrapper rw = Rest_MTM_MisureCustomer.doPost(mW);
        System.debug(rw);
            
            }
        Test.stopTest();

        
    }
    @isTest static void test_PostSarto(){
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        usr.Codice_Boutique__c = '001';
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
        
        Account acc = AllDataFactory.create_Account();
        insert acc;
        
        //MC- To test order attachments process
        Location__c c = new Location__c();
        insert c;
               
        Associated__c t = new Associated__c();
        t.Id_Associate_Micros__c = '123456789';
        t.Location__c = c.Id;
        insert t;
        
        Ordine_Sartoria_Solomeo__c oss = new Ordine_Sartoria_Solomeo__c();
        oss.Associate__c = t.id;
        insert oss;
        string ossname = [SELECT Name FROM Ordine_Sartoria_Solomeo__c WHERE Id=:oss.Id].Name;
        //insert attachments order
        List<Attachment> aList = new List<Attachment>();
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'pdf_' + ossname + '.pdf', 'pdf'));
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'pdf_cliente_' + ossname + '.pdf', 'pdf'));
        aList.add(ALLDataFactory.create_Attachment(oss.Id, 'img_' + ossname + '.png', 'png'));
        insert aList;
        //MC-
        
        Account_Misure_Sartoriali__c ams  = AllDataFactory.create_Account_Misure_Sartoriali();
		ams.Account__c = acc.Id;
        ams.Ordine_Sartoria_Solomeo__c = oss.id;
        insert ams;
		
        //MC- to test order attachments process
        List<Rest_MTM_MisureCustomer.AttachWrapper> awList = new List<Rest_MTM_MisureCustomer.AttachWrapper>();
        awList.add(ALLDataFactory.create_postAttachWrapper('pdf','pdf','testRest1'));
        awList.add(ALLDataFactory.create_postAttachWrapper('pdf','pdf_cliente','testRest1'));
        awList.add(ALLDataFactory.create_postAttachWrapper('png','img','testRest1'));
        
        req.requestURI =    '/MTM/V1/Misure/'; 
        req.httpMethod = 'Post';
        
        RestContext.response= res;
        RestContext.request = req;
        
        ams.Circonferenza_vita_pantalone__c = 32;
        ams.Circonferenza_torace__c = 30;
       	Rest_MTM_MisureCustomer.MisureWrapper mW = new Rest_MTM_MisureCustomer.MisureWrapper();
        mW.step = 'U';
        mW.profilo = 'Sarto';
        mW.data = ams;
        mW.data.Id = ams.Id;
        mW.attachments = awList;
        
        
        ResponseWrapper rw = Rest_MTM_MisureCustomer.doPost(mW);
        System.debug(rw);
        
            }
        Test.stopTest();
    }
    
    @isTest static void test_get1() {
        //new Rest_MTM_MisureCustomer.RestMisureCustomerHandler().beforeUpdate(null, null, SObject(oss));
        new Rest_MTM_MisureCustomer.RestMisureCustomerHandler().afterUpdateResponse(null, null, null);
        new Rest_MTM_MisureCustomer.RestMisureCustomerHandler().beforeInsert(null);
        new Rest_MTM_MisureCustomer.RestMisureCustomerHandler().afterInsert(null);
        
        //MC- PassTest
        //Rest_MTM_MisureCustomer.passTest();
    }
}