src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Privacy_1__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Customer acceptance of the Privacy Statement</inlineHelpText>
        <label>Consenso marketing (old)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/onTransactionTriggerHandlerTest.cls
@isTest
public class onTransactionTriggerHandlerTest {

    static testMethod void CreateGiftActivityTest() {     
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            Account a1 	= new Account();
            a1.LastName = 'TestLastName1';
            a1.Privacy_1__c = true;
            insert a1;
            
            Product__c p 	= new Product__c();
            p.Name		= 'ProductTest';
            insert p;
            
            Transaction__c t 	= new Transaction__c();
            t.Account__c		= a1.Id;
            insert t;
            
        
        }
        Test.stopTest();
        
        
    }
}