src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Misure_Sartoriali__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Schede_Misura_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Altezza_montante_davanti__c</fullName>
        <label>Altezza montante davanti</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Altezza_montante_dietro__c</fullName>
        <label>Altezza montante dietro</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circonferenza_bacino__c</fullName>
        <label>Circonferenza bacino</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circonferenza_torace__c</fullName>
        <label>Circonferenza torace</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circonferenza_vita_giacca__c</fullName>
        <label>Circonferenza vita (giacca)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Circonferenza_vita_pantalone__c</fullName>
        <label>Circonferenza vita (pantalone)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Curvo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Curvo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Forte_panciuto__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Forte panciuto</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Larghezza_coscia__c</fullName>
        <label>Larghezza coscia</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_fondo__c</fullName>
        <label>Larghezza fondo</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_ginocchio__c</fullName>
        <label>Larghezza ginocchio</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_manica_bicipite__c</fullName>
        <label>Larghezza manica bicipite</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_manica_fondo__c</fullName>
        <label>Larghezza manica fondo</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_polpaccio__c</fullName>
        <label>Larghezza polpaccio</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_spalle_pt_to_pt__c</fullName>
        <label>Larghezza spalle pt. to pt.</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_giacca_dietro__c</fullName>
        <label>Lungh. giacca dietro</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_manica_destra_cucitura_interna__c</fullName>
        <label>Lungh. manica destra (cucitura interna)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_manica_sinistra_cucitura_interna__c</fullName>
        <label>Lungh. manica sinistra(cucitura interna)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Normale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Normale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rovesciato__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rovesciato</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Semi_bacino__c</fullName>
        <label>Semi bacino</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Semi_torace__c</fullName>
        <label>Semi torace</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Semi_vita__c</fullName>
        <label>Semi vita</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spalle_Alte__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spalle Alte</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spalle_Basse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spalle Basse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Spalle_Regolari__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Spalle Regolari</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stomaco_prominente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stomaco prominente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Taglia__c</fullName>
        <label>Taglia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Scheda Misure Sartoria Solomeo</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Nome Scheda Misura Sartoria Solomeo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schede Misure Sartoria Solomeo</pluralLabel>
    <recordTypes>
        <fullName>Pantalone</fullName>
        <active>true</active>
        <label>Pantalone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Misure_di_Riferimento_Sartoria__c.object
<CustomObject>
    <fields>
        <fullName>Altezza_montante_davanti__c</fullName>
        <label>Altezza montante davanti</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Altezza_montante_dietro__c</fullName>
        <label>Altezza montante dietro</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_coscia__c</fullName>
        <label>Larghezza coscia</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_fondo__c</fullName>
        <label>Larghezza fondo</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_ginocchio__c</fullName>
        <label>Larghezza ginocchio</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_manica_bicipite__c</fullName>
        <label>Larghezza manica bicipite</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_manica_fondo__c</fullName>
        <label>Larghezza manica fondo</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_polpaccio__c</fullName>
        <label>Larghezza polpaccio</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Larghezza_spalle_pt_to_pt__c</fullName>
        <label>Larghezza spalle pt. to pt.</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_giacca_dietro__c</fullName>
        <label>Lungh. giacca dietro</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_manica_destra_cucitura_interna__c</fullName>
        <label>Lungh. manica destra (cucitura interna)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lungh_manica_sinistra_cucitura_interna__c</fullName>
        <label>Lungh. manica sinistra(cucitura interna)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Semi_bacino__c</fullName>
        <label>Semi bacino</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Semi_torace__c</fullName>
        <label>Semi torace</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Semi_vita__c</fullName>
        <label>Semi vita</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Taglia__c</fullName>
        <label>Taglia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Misura di Riferimento Sartoria</label>
    <nameField>
        <label>Nome Misura di Riferimento Sartoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Misure di Riferimento Sartoria</pluralLabel>
    <recordTypes>
        <fullName>Pantalone</fullName>
        <active>true</active>
        <label>Pantalone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Id_Admin_Apex__c</fullName>
        <label>Id Admin Apex</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Xstore_Apex__c</fullName>
        <label>Id Xstore Apex</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <recordTypes>
        <fullName>Boutique</fullName>
        <active>true</active>
        <description>Boutique</description>
        <label>Boutique</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translate__c.object
<CustomObject>
    <fields>
        <fullName>Subheader_Label__c</fullName>
        <label>Subheader_Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Translate</label>
    <nameField>
        <label>ISO Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AllDataFactory.cls
/*
 * @Author svella
 */
public class AllDataFactory {
    
    public static User create_User() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User result = new User(
            Alias = 'standt1',
            Email='user1@testorg.com',
            EmailEncodingKey='UTF-8', 
            LastName='Testing1', 
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            Extension = '9988',
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='standard1@testorg.com'
        );
        
        return result;
    }
    
    public static User create_UserWithProfile(string TestProfileId) {
        User result = new User(                                                                             
            LastName                    = 'Utente Test',                                        
            CommunityNickname           = 'communitynicknameTest',                              
            Alias                       = 'UserTest',                                                                                                       
            ProfileId                   = TestProfileId,                            
            Email                       = 'test@test.com',                                                                                                          
            Username                    = 'test.User@testr.name',                       
            EmailEncodingKey            = 'ISO-8859-1',                 
            TimeZoneSidKey              = 'Europe/Rome',                        
            LanguageLocaleKey           = 'it',                 
            LocaleSidKey                = 'it_IT'                           
        );
        return result;
    }
    
    public static Account create_Account() {
        RecordType personAccountRecordType =  [SELECT Id FROM RecordType where SobjectType='Account' and Developername='PersonAccount'];
        
        Account result = new Account(
            FirstName = 'TestName',
            LastName = 'TestSurname',
            Sesso__c = 'M',
            PersonEmail =  'personalEmail@gmail.com',
            Phone = '12345679',
            PersonMobilePhone = '16844838',
            RecordTypeId = personAccountRecordType.Id
        );

        return result;
    }
    
    public static Product__c create_Product() {
        Account acc = [SELECT Id FROM Account WHERE PersonEmail='personalEmail@gmail.com'];
        Product__c result = new Product__c(
            Name = 'test_product'
        );
        
        return result;
    }
    
    public static Transaction__c create_Transactions() {
        RecordType transactionRecordType =  [SELECT Id FROM RecordType where SobjectType='Transaction__c' and Developername='Boutique'];
        Account acc = [SELECT Id FROM Account WHERE PersonEmail='personalEmail@gmail.com'];
        
        Transaction__c result = new Transaction__c(
            Name     = '1234567890',
            Account__c = acc.Id,
            RecordTypeId = transactionRecordType.Id
        );
        
        return result;
    }
    
    public static Transaction_Detail__c create_Transaction_Details() {
        Transaction__c trans = [SELECT Id FROM Transaction__c WHERE Name='1234567890'];
        Account acc = [SELECT Id FROM Account WHERE PersonEmail='personalEmail@gmail.com'];
        Product__c prod = [SELECT Id FROM Product__c WHERE Name='test_product'];
        
        Transaction_Detail__c result = new Transaction_Detail__c(
            Name     = '0987654321',
            Transaction__c = trans.Id,
            Product__c = prod.Id
        );
        
        return result;
    }
    
    public static Attachment create_Attachment(Id accountId) {
        Attachment result = new Attachment(
            Name='Unit Test Attachment',
        body=Blob.valueOf('Unit Test Attachment Body'),
        parentId = accountId
        );
        
        return result;
    }
    
    //MC- Attachments
    public static attachment create_Attachment(Id parent,string name,string attachtype){
        Attachment attach=new Attachment();
        attach.Name = (name != null) ? name : 'test_attachment'; 
        Blob bodyBlob = Blob.valueOf('TestTestAndTestagain'); 
        attach.body = bodyBlob; 
        attach.parentId = parent; 
        attach.ContentType = (attachtype != null) ? 'application/' + attachtype : 'application/pdf'; 
        attach.IsPrivate = false; 
        attach.Description = 'Test'; 
        
        return attach;
    }
    
    public static ContentVersion create_ContentVersion() {
        ContentVersion result = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        
        return result;
    }
    
    public static ContentDocumentLink create_ContentDocumentLink(ContentVersion cv) {
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        ContentDocumentLink result = new ContentDocumentLink(
            ContentDocumentId = conDoc,
             ShareType = 'I'
         );
        
        return result;
    }
    
    public static ContentDocumentLink create_ContentDocumentLink(ContentVersion cv, Transaction_Detail__c detail) {
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        ContentDocumentLink result = new ContentDocumentLink(
            ContentDocumentId = conDoc,
             LinkedEntityId = detail.Product__c,
             ShareType = 'I'
         );
        
        return result;
    }
    
    // ACTIVATE FOR REGISTRATION FORM
    
    public static Translate__c create_Translator() {
        
        
        Translate__c result = new Translate__c(
            Name = 'en_US',
            Subheader_Label__c = 'subheader'
        );
        
        return result;
    }
    
     public static Profile__c create_TriggerSetting(String ProfileId) {
        
        Profile__c result = new Profile__c(
            Id_Admin_Apex__c = ProfileId,
            Id_Xstore_Apex__c = '00e36000000ebXdAAI'
        );

        return result;
    }
    
    // MTM    
    public static Account_Misure_Sartoriali__c create_Account_Misure_Sartoriali() {
        RecordType misureRecordType =  [SELECT Id FROM RecordType where SobjectType='Account_Misure_Sartoriali__c' and Developername='Pantalone'];
        Account_Misure_Sartoriali__c result = new Account_Misure_Sartoriali__c(
            
            Altezza_montante_davanti__c = 10,
            Altezza_montante_dietro__c = 12,
            Circonferenza_bacino__c = 13,
            Circonferenza_torace__c = 14,
            Circonferenza_vita_giacca__c = 13,
            Circonferenza_vita_pantalone__c = 12,
            Curvo__c = true,
            Forte_panciuto__c = true,
            Larghezza_coscia__c = 12,
            Larghezza_fondo__c = 13,
            Larghezza_ginocchio__c = 14,
            Larghezza_manica_bicipite__c = 12,
            Larghezza_manica_fondo__c = 14,
            Larghezza_polpaccio__c = 12,
            Larghezza_spalle_pt_to_pt__c = 21,
            Lungh_giacca_dietro__c = 34,
            Lungh_manica_destra_cucitura_interna__c = 21,
            Normale__c = false,
            RecordTypeId = misureRecordType.Id,
            Rovesciato__c = true,
            Semi_bacino__c = 12,
            Semi_torace__c = 14,
            Semi_vita__c = 23,
            Spalle_Alte__c = true,
            Spalle_Basse__c = true,
            Spalle_Regolari__c = true,
            Stomaco_prominente__c = true,
            Taglia__c = 'taglia text'
        );
        
        return result;
    }
    
    public static Misure_di_Riferimento_Sartoria__c create_Misure_di_Riferimento_Sartoria(String rtDevName) {
        RecordType misureRecordType =  [SELECT Id FROM RecordType where SobjectType='Misure_di_Riferimento_Sartoria__c' and Developername=: rtDevName];
        Misure_di_Riferimento_Sartoria__c result = new Misure_di_Riferimento_Sartoria__c(
            Altezza_montante_davanti__c = 10,
            Altezza_montante_dietro__c = 10,
            Larghezza_coscia__c = 10,
            Larghezza_fondo__c = 10,
            Larghezza_ginocchio__c = 10,
            Larghezza_manica_bicipite__c = 10,
            Larghezza_manica_fondo__c = 10,
            Larghezza_polpaccio__c = 10,
            Larghezza_spalle_pt_to_pt__c = 10,
            Lungh_giacca_dietro__c = 10,
            Lungh_manica_destra_cucitura_interna__c = 10,
            Lungh_manica_sinistra_cucitura_interna__c = 10,
            Semi_bacino__c = 10,
            Semi_torace__c = 10,
            Semi_vita__c = 10,
            RecordType = misureRecordType,
            Taglia__c = '10'
        );
        
        return result;
    }
    
    public static Rest_MTM_MisureCustomer.AttachWrapper create_postAttachWrapper(string format,string type,string staticResourceName){
        Rest_MTM_MisureCustomer.AttachWrapper aw = new Rest_MTM_MisureCustomer.AttachWrapper();
        string data = [SELECT Body FROM StaticResource WHERE Name =:staticResourceName].Body.toString();
        aw.format = format;
        aw.type = type;
        aw.attachment = data;
        
        return aw;
    }
    
    public static MTM_Alert__c create_MTM_Alert(String loc, String step, String recipient, String role){
        MTM_Alert__c result =new MTM_Alert__c();
        
        result.Location__c = loc;
        result.Step__c = step;
        result.Email__c = 'test@test.it';
        result.Recipient_Type__c = recipient;
        result.Role__c = role;
        
        return result;
    }
    
    
}