src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Di_Registrazione__c</fullName>
        <label>Data Di Registrazione</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_xStore__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente xStore</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lingua__c</fullName>
        <label>Lingua</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ar</fullName>
                    <label>Arabic</label>
                </value>
                <value>
                    <fullName>bg</fullName>
                    <label>Bulgarian</label>
                </value>
                <value>
                    <fullName>cs</fullName>
                    <label>Czech</label>
                </value>
                <value>
                    <fullName>da</fullName>
                    <label>Danish</label>
                </value>
                <value>
                    <fullName>nl</fullName>
                    <label>Dutch</label>
                </value>
                <value>
                    <fullName>en</fullName>
                    <label>English</label>
                </value>
                <value>
                    <fullName>et</fullName>
                    <label>Estonian</label>
                </value>
                <value>
                    <fullName>fi</fullName>
                    <label>Finnish</label>
                </value>
                <value>
                    <fullName>fr</fullName>
                    <label>French</label>
                </value>
                <value>
                    <fullName>de</fullName>
                    <label>German</label>
                </value>
                <value>
                    <fullName>el</fullName>
                    <label>Greek</label>
                </value>
                <value>
                    <fullName>he</fullName>
                    <label>Hebrew</label>
                </value>
                <value>
                    <fullName>hu</fullName>
                    <label>Hungarian</label>
                </value>
                <value>
                    <fullName>it</fullName>
                    <label>Italian</label>
                </value>
                <value>
                    <fullName>ko</fullName>
                    <label>Korean</label>
                </value>
                <value>
                    <fullName>lv</fullName>
                    <label>Latvian</label>
                </value>
                <value>
                    <fullName>lt</fullName>
                    <label>Lithuanian</label>
                </value>
                <value>
                    <fullName>no</fullName>
                    <label>Norwegian</label>
                </value>
                <value>
                    <fullName>pl</fullName>
                    <label>Polish</label>
                </value>
                <value>
                    <fullName>pt</fullName>
                    <label>Portuguese</label>
                </value>
                <value>
                    <fullName>ro</fullName>
                    <label>Romanian</label>
                </value>
                <value>
                    <fullName>sk</fullName>
                    <label>Slovak</label>
                </value>
                <value>
                    <fullName>sl</fullName>
                    <label>Slovenian</label>
                </value>
                <value>
                    <fullName>es</fullName>
                    <label>Spanish</label>
                </value>
                <value>
                    <fullName>sv</fullName>
                    <label>Swedish</label>
                </value>
                <value>
                    <fullName>th</fullName>
                    <label>Thai</label>
                </value>
                <value>
                    <fullName>tr</fullName>
                    <label>Turkish</label>
                </value>
                <value>
                    <fullName>uk</fullName>
                    <label>Ucrainian</label>
                </value>
                <value>
                    <fullName>ru</fullName>
                    <label>русскийязык</label>
                </value>
                <value>
                    <fullName>ja</fullName>
                    <label>日本語</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Messaging__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Instant Messaging</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nazionalita__c</fullName>
        <label>Nazionalità</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AX</fullName>
                    <label>Aaland Islands</label>
                </value>
                <value>
                    <fullName>AF</fullName>
                    <label>Afghanistan</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                    <label>Albania</label>
                </value>
                <value>
                    <fullName>DZ</fullName>
                    <label>Algeria</label>
                </value>
                <value>
                    <fullName>AS</fullName>
                    <label>American Samoa</label>
                </value>
                <value>
                    <fullName>AD</fullName>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>AO</fullName>
                    <label>Angola</label>
                </value>
                <value>
                    <fullName>AI</fullName>
                    <label>Anguilla</label>
                </value>
                <value>
                    <fullName>AQ</fullName>
                    <label>Antarctica</label>
                </value>
                <value>
                    <fullName>AG</fullName>
                    <label>Antigua And Barbuda</label>
                </value>
                <value>
                    <fullName>AR</fullName>
                    <label>Argentina</label>
                </value>
                <value>
                    <fullName>AM</fullName>
                    <label>Armenia</label>
                </value>
                <value>
                    <fullName>AW</fullName>
                    <label>Aruba</label>
                </value>
                <value>
                    <fullName>AU</fullName>
                    <label>Australia</label>
                </value>
                <value>
                    <fullName>AT</fullName>
                    <label>Austria</label>
                </value>
                <value>
                    <fullName>AZ</fullName>
                    <label>Azerbaijan</label>
                </value>
                <value>
                    <fullName>BS</fullName>
                    <label>Bahamas</label>
                </value>
                <value>
                    <fullName>BH</fullName>
                    <label>Bahrain</label>
                </value>
                <value>
                    <fullName>BD</fullName>
                    <label>Bangladesh</label>
                </value>
                <value>
                    <fullName>BB</fullName>
                    <label>Barbados</label>
                </value>
                <value>
                    <fullName>BY</fullName>
                    <label>Belarus</label>
                </value>
                <value>
                    <fullName>BE</fullName>
                    <label>Belgium</label>
                </value>
                <value>
                    <fullName>BZ</fullName>
                    <label>Belize</label>
                </value>
                <value>
                    <fullName>BJ</fullName>
                    <label>Benin</label>
                </value>
                <value>
                    <fullName>BM</fullName>
                    <label>Bermuda</label>
                </value>
                <value>
                    <fullName>BT</fullName>
                    <label>Bhutan</label>
                </value>
                <value>
                    <fullName>BO</fullName>
                    <label>Bolivia</label>
                </value>
                <value>
                    <fullName>BA</fullName>
                    <label>Bosnia And Herzegowina</label>
                </value>
                <value>
                    <fullName>BW</fullName>
                    <label>Botswana</label>
                </value>
                <value>
                    <fullName>BV</fullName>
                    <label>Bouvet Island</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Posta__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Postal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Privacy1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consenso marketing BC spa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Privacy2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consenso marketing BC group</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Privacy3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consenso profilazione</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Professione__c</fullName>
        <label>Professione</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Legal Affairs</fullName>
                </value>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Ceo</fullName>
                </value>
                <value>
                    <fullName>Politician</fullName>
                </value>
                <value>
                    <fullName>Fashion Business</fullName>
                </value>
                <value>
                    <fullName>Architect/Designer</fullName>
                </value>
                <value>
                    <fullName>Banker</fullName>
                </value>
                <value>
                    <fullName>Military/Law Enforcement</fullName>
                </value>
                <value>
                    <fullName>Social Worker</fullName>
                </value>
                <value>
                    <fullName>Editor/Publisher</fullName>
                </value>
                <value>
                    <fullName>Journalist</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Financial Investor/Analyst</fullName>
                </value>
                <value>
                    <fullName>Craftsman</fullName>
                </value>
                <value>
                    <fullName>Housewife</fullName>
                </value>
                <value>
                    <fullName>Diplomat</fullName>
                </value>
                <value>
                    <fullName>Pr/Advertising</fullName>
                </value>
                <value>
                    <fullName>Movie/Theather Business</fullName>
                </value>
                <value>
                    <fullName>Educationalist</fullName>
                </value>
                <value>
                    <fullName>Freelance</fullName>
                </value>
                <value>
                    <fullName>Artist</fullName>
                </value>
                <value>
                    <fullName>Healthcare specialist</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Gourmet</fullName>
                </value>
                <value>
                    <fullName>Travel businessman</fullName>
                </value>
                <value>
                    <fullName>Human Arts</fullName>
                </value>
                <value>
                    <fullName>Influencer/Celebrity</fullName>
                </value>
                <value>
                    <fullName>Sportsman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Social__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS/MMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RussianWebServerLog__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HttpResponseCode__c</fullName>
        <label>HttpResponseCode</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResubmitNumber__c</fullName>
        <label>ResubmitNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XMLRequest__c</fullName>
        <label>XMLRequest</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>XMLResponse__c</fullName>
        <label>XMLResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>RussianWebServerLog</label>
    <nameField>
        <label>RussianWebServerLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RussianWebServerLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RussianWebServer.cls
public class RussianWebServer {

    public static void RussianWebServerXMLInvocation(RussianWebServerLog__c log){
        try{
        log.ResubmitNumber__c = log.ResubmitNumber__c + 1;
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setHeader('Content-Type', 'text/xml; charset=UTF-8');
        req.setHeader('SOAPAction', 'blank');
        req.setEndpoint('https://srvesb.brunellocucinelli.com:8085/secured/dispatch/russia/CustomerServicesApi/addOrUpdateCustomer');
        req.setTimeout(10000); // timeout in milliseconds
        req.setBody(log.XMLRequest__c);
        Http http = new Http();             
        HTTPResponse res = http.send(req);
        system.debug('DEBUG@ RESPONSE: ' + res);
        system.debug('DEBUG@ RESPONSE BODY: ' + res.getBody());
        system.debug('DEBUG@ RESPONSE STATUS: ' + res.getStatus());
        system.debug('DEBUG@ RESPONSE STATUS CODE: ' + res.getStatusCode());
        log.HttpResponseCode__c = res.getStatusCode();
        log.XMLResponse__c = res.getBody();
        log.ErrorMessage__c = '';
        update log;
        }
        catch(Exception e){
            System.debug(e);
            log.ErrorMessage__c = e.getMessage();
            update log;
            
        }
    }    
public static void RussianWebServerInvocation(Account acc){
    RussianWebServerLog__c log = new RussianWebServerLog__c();
    
	log.Name = acc.Id;
    log.ResubmitNumber__c = 0;
	User user = [SELECT id,Alias FROM User WHERE Id=:UserInfo.getUserId()];
    
    try{
            String xml_storeId = (acc.Id_Location__c == null ? '' : acc.Id_Location__c);
            String xml_name = (acc.FirstName == null ? '' : acc.FirstName);
            String xml_lastName = (acc.LastName == null ? '' : acc.LastName);
            String xml_salutation = (acc.Salutation == null ? '' : acc.Salutation);
            String xml_personMailingStreet = (acc.PersonMailingStreet == null ? '' : acc.PersonMailingStreet);
            String xml_personMailingCity = (acc.PersonMailingCity == null ? '' : acc.PersonMailingCity);
            String xml_personMailingCountry = (acc.PersonMailingCountry == null ? '' : acc.PersonMailingCountry);
			String xml_personMailingPostalCode = (acc.PersonMailingPostalCode == null ? '' : acc.PersonMailingPostalCode);
            String xml_email = (acc.PersonEmail == null ? '' : acc.PersonEmail);
			String xml_phone = (acc.Phone == null ? '' : acc.Phone);
			String xml_sesso = (acc.Sesso__c == null ? '' : acc.Sesso__c);
			String xml_birthdate = (acc.PersonBirthdate == null ? '' : Datetime.newInstance(acc.PersonBirthdate, Time.newInstance(0,0,0,0)).format('yyyy-MM-dd'));
            String xml_language = (acc.Lingua__c == null ? '' : acc.Lingua__c);
            String xml_PhoneContact = (acc.Telefono__c == null || acc.Telefono__c == false ? 'false' : 'true');
			String xml_EmailContact = (acc.Email__c == null || acc.Email__c == false ? 'false' : 'true');
            String xml_PostalContact = (acc.Posta__c == null || acc.Posta__c == false ? 'false' : 'true');
			String xml_xStroreId = (acc.Id_Cliente_xStore__c == null ? '' : acc.Id_Cliente_xStore__c);
			String xml_occupation = (acc.Professione__c == null ? '' : acc.Professione__c);
            String xml_nationality = (acc.Nazionalita__c == null ? '' : acc.Nazionalita__c);
			String xml_marketingBC = (acc.Privacy1__c == null || acc.Privacy1__c == false ? 'FALSE' : 'TRUE'); 
            String xml_marketingBCGroup = (acc.Privacy2__c == null || acc.Privacy2__c == false ? 'FALSE' : 'TRUE');
            String xml_marketingProfile = (acc.Privacy3__c == null || acc.Privacy3__c == false ? 'FALSE' : 'TRUE');
            String xml_SMS = (acc.Social__c == null || acc.Social__c == false ? 'FALSE' : 'TRUE');
            String xml_istantMessage = (acc.Messaging__c == null || acc.Messaging__c == false ? 'FALSE' : 'TRUE');
			String xml_registrationDate= (acc.Data_Di_Registrazione__c == null ? '' : Datetime.newInstance(acc.Data_Di_Registrazione__c, Time.newInstance(0,0,0,0)).format('yyyy-MM-dd'));
			String xml_now = Datetime.now().format('yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX');
            String xml_ageRange = (acc.Fascia_Di_Eta__c == null ? '' : acc.Fascia_Di_Eta__c);
            
            HttpRequest req = new HttpRequest();
            req.setMethod('POST');
            req.setHeader('Content-Type', 'text/xml; charset=UTF-8');
            req.setHeader('SOAPAction', 'blank');
            req.setEndpoint('https://srvesb.brunellocucinelli.com:8085/secured/dispatch/russia/CustomerServicesApi/addOrUpdateCustomer'); 
           	 
          String xml = '<?xml version="1.0" encoding="UTF-8"?>'+
            	'<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">'+
                '  <S:Body>'+
                	'<ns2:addOrUpdateCustomer xmlns:ns2="http://v2_3.customer.webservices.csx.dtv.com/">'+
                		'<customerData>'+
                			'<RetailStoreID>'+xml_storeId+'</RetailStoreID>'+
                			'<Instrument />'+
                			'<BusinessName>Brunello Cucinelli S.P.A.</BusinessName>'+
                			'<Prospect>false</Prospect>'+
                			'<LastUpdateInfo>'+
                				'<UpdateUserID>'+'SF - '+ user.Alias+'</UpdateUserID>'+
                				'<UpdateDate>'+xml_now+'</UpdateDate>'+
                			'</LastUpdateInfo>'+
                '        <Affiliation>'+
                '          <RetailStoreID>'+xml_storeId+'</RetailStoreID>'+
                '        </Affiliation>'+
                '        <EntityInformation>'+
                '          <Individual>'+
                '            <Name>'+
                '              <Name Location="First">'+xml_name+'</Name>'+
                '              <Name Location="Last">'+xml_lastName+'</Name>'+
                '            </Name>'+
                '            <Salutation>'+xml_salutation+'</Salutation>'+
                '            <ContactInformation>'+
                '              <Address ContactPreferenceCode="Y" PrimaryFlag="true" TypeCode="HOME">'+
                '                <AddressLine1>'+xml_personMailingStreet+'</AddressLine1>'+
                '                <AddressLine2>-</AddressLine2>'+
                '                <AddressLine3>-</AddressLine3>'+
                '                <AddressLine4>-</AddressLine4>'+
                '                <ApartmentNumber>-</ApartmentNumber>'+
                '                <City>'+xml_personMailingCity+'</City>'+
                '                <Country>'+xml_personMailingCountry+'</Country>'+
                '                <Territory></Territory>'+
                '                <PostalCode>'+xml_personMailingPostalCode+'</PostalCode>'+
                '              </Address>'+
                '              <EMail ContactPreferenceCode="N" PrimaryFlag="true" TypeCode="Home">'+
                '                <EMailAddress>'+xml_email+'</EMailAddress>'+
                '              </EMail>'+
                '              <Telephone ContactPreferenceCode="N" PrimaryFlag="true" TypeCode="HOME">'+
                '                <PhoneNumber>'+xml_phone+'</PhoneNumber>'+
                '              </Telephone>'+
                '            </ContactInformation>'+
                '            <PersonalSummary>'+
                '              <GenderType>'+xml_sesso+'</GenderType>'+
                '              <BirthDate>'+xml_birthdate+'</BirthDate>'+
                '              <Rent>false</Rent>'+
                '              <LanguageCode>'+xml_language+'</LanguageCode>'+
                '            </PersonalSummary>'+
                '          </Individual>'+
                '        </EntityInformation>'+
                '        <PersonalPreferences>'+
                '          <ContactPreference ContactType="Email" Permission="'+xml_EmailContact+'" />'+
                '          <ContactPreference ContactType="Phone" Permission="'+xml_PhoneContact+'" />'+
                '          <ContactPreference ContactType="Mail" Permission="'+xml_PostalContact+'" />'+
                '        </PersonalPreferences>'+
                '        <CustomAttribute name="OCCUPATION">'+
                '          <AttributeValue>'+xml_occupation+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="NATIONALITY">'+
                '          <AttributeValue>'+xml_nationality+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="DATE_RANGE">'+
                '          <AttributeValue>'+xml_ageRange+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="MARKETING_BC_SPA_FLAG">'+
                '          <AttributeValue>'+xml_marketingBC+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="PROFILING_FLAG">'+
                '          <AttributeValue>'+xml_marketingProfile+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="MARKETING_BC_GROUP_FLAG">'+
                '          <AttributeValue>'+xml_marketingBCGroup+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="PHONE_CONTACT_FLAG">'+
                '          <AttributeValue>'+xml_PhoneContact+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="EMAIL_FLAG">'+
                '          <AttributeValue>'+xml_EmailContact+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="PAPER_MAIL_FLAG">'+
                '          <AttributeValue>'+xml_PostalContact+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="SMS_FLAG">'+
                '          <AttributeValue>'+xml_SMS+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="INSTANT_MESSAGING_FLAG">'+
                '          <AttributeValue>'+xml_istantMessage+'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="LAST_UPDATE">'+
                '          <AttributeValue>'+ xml_registrationDate +'</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="PARTY_TYPE_CODE">'+
                '          <AttributeValue>CUSTOMER</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="ACTIVE_FLAG">'+
                '          <AttributeValue>true</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <CustomAttribute name="PROMPT_TO_JOIN_LOYALTY">'+
                '          <AttributeValue>true</AttributeValue>'+
                '        </CustomAttribute>'+
                '        <SignupDate>'+xml_registrationDate+'</SignupDate>'+
                '      </customerData>'+
                '      <securityUserId>100</securityUserId>'+
                '    </ns2:addOrUpdateCustomer>'+
                '  </S:Body>'+
                '</S:Envelope>';
            
        	log.XMLRequest__c = xml;
            req.setTimeout(10000); // timeout in milliseconds
            req.setBody(xml);
            Http http = new Http();             
            HTTPResponse res = http.send(req);
            system.debug('DEBUG@ RESPONSE: ' + res);
            system.debug('DEBUG@ RESPONSE BODY: ' + res.getBody());
            system.debug('DEBUG@ RESPONSE STATUS: ' + res.getStatus());
            system.debug('DEBUG@ RESPONSE STATUS CODE: ' + res.getStatusCode());
            
            
            log.HttpResponseCode__c = res.getStatusCode();
            log.XMLResponse__c = res.getBody();
        	insert log;
            
        }
        catch(Exception e){
            System.debug(e);
            log.ErrorMessage__c = e.getMessage();
            insert log;
            
        }
    }
}