src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Categoria_Cliente_Proposta__c</fullName>
        <description>Campo categoria cliente utilizzata per richiedere l&apos;approvazione della categoria cliente ufficiale in sola lettura</description>
        <label>Categoria cliente proposta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VIP5</fullName>
                </value>
                <value>
                    <fullName>VIP10</fullName>
                </value>
                <value>
                    <fullName>VIP15</fullName>
                </value>
                <value>
                    <fullName>VIP20</fullName>
                </value>
                <value>
                    <fullName>VIP30</fullName>
                </value>
                <value>
                    <fullName>VIP40</fullName>
                </value>
                <value>
                    <fullName>VHK10</fullName>
                </value>
                <value>
                    <fullName>VHK15</fullName>
                </value>
                <value>
                    <fullName>VHK30</fullName>
                </value>
                <value>
                    <fullName>VCN10</fullName>
                </value>
                <value>
                    <fullName>VCN15</fullName>
                </value>
                <value>
                    <fullName>VCN20</fullName>
                </value>
                <value>
                    <fullName>VCN30</fullName>
                </value>
                <value>
                    <fullName>VJP05</fullName>
                </value>
                <value>
                    <fullName>VJP10</fullName>
                </value>
                <value>
                    <fullName>E-IT</fullName>
                </value>
                <value>
                    <fullName>E-EU</fullName>
                </value>
                <value>
                    <fullName>E-US</fullName>
                </value>
                <value>
                    <fullName>E-OT</fullName>
                </value>
                <value>
                    <fullName>VRU10</fullName>
                </value>
                <value>
                    <fullName>VRU15</fullName>
                </value>
                <value>
                    <fullName>PS</fullName>
                </value>
                <value>
                    <fullName>BOARD60</fullName>
                </value>
                <value>
                    <fullName>B60</fullName>
                </value>
                <value>
                    <fullName>AGENTS30</fullName>
                </value>
                <value>
                    <fullName>CONF20</fullName>
                </value>
                <value>
                    <fullName>PS10</fullName>
                </value>
                <value>
                    <fullName>PS15</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivazione_Richiesta_Sconto__c</fullName>
        <label>Motivazione Richiesta Sconto</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Nation_Contact_Card__c</fullName>
        <label>Nation Contact Card</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Nation</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DiscountCategoriesController.cls
public class DiscountCategoriesController {

    @AuraEnabled
    public static User getUserInfo(){
        return [SELECT ID, Name, Nation_Contact_Card__c,ManagerID FROM User WHERE ID=: UserInfo.getUserId()];
    } 
    
    @AuraEnabled
    public static List<Discount_Category_Visibility__mdt> getPicklistValue(){
        String userCountry = getUserInfo().Nation_Contact_Card__c;

        List<Discount_Category_Visibility__mdt> listDisc = new List<Discount_Category_Visibility__mdt>(); 

        if(userCountry!= null){
            userCountry= '%'+userCountry+'%';
            System.debug('VS check userCountry: '+userCountry);
            listDisc =[SELECT DeveloperName, Country__c, ProposedCustomerCategory__c
                        FROM Discount_Category_Visibility__mdt
                        WHERE Country__c LIKE: userCountry
                        ORDER BY DeveloperName ];
        }else{
            listDisc = [SELECT DeveloperName, Country__c, ProposedCustomerCategory__c
                        FROM Discount_Category_Visibility__mdt
                        WHERE Country__c = null
                        ORDER BY DeveloperName];
        }
        return listDisc;
    }

    @AuraEnabled
    public static void updateAccount(string recordId,String categoria, String motivo){
        Account acc = new Account(ID = recordId,
                                 Categoria_Cliente_Proposta__c = categoria,
                                 Motivazione_Richiesta_Sconto__c = motivo);      
        if(!Test.isRunningTest()){
            update acc;
        }

    }
}