src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente E-commerce</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente AS400</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Ordine__c</fullName>
        <label>Id Ordine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Reso__c</fullName>
        <label>Id Reso</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Store__c</fullName>
        <label>Id Store</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Casi</relationshipLabel>
        <relationshipName>Casi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origine_Ticket__c</fullName>
        <label>Origine Ticket</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prodotto_Selezionato__c</fullName>
        <label>Prodotto Selezionato</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipologia__c</fullName>
        <label>Tipologia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Brand_Specialist</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Brand Specialist</description>
        <label>Brand Specialist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reso_Cambio</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Reso/Cambio</description>
        <label>Reso/Cambio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reso_Cambio_in_Store</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Reso/Cambio in Store</description>
        <label>Reso/Cambio in Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_E_commerce</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Ticket E-commerce</description>
        <label>Ticket E-commerce</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_E_commerce_Notify_Me</fullName>
        <active>true</active>
        <businessProcess>Notify Me</businessProcess>
        <label>Ticket E-commerce – Notify Me</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_OMS</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Ticket OMS</description>
        <label>Ticket OMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <externalId>true</externalId>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Caso_BrandSpecialist__c</fullName>
        <label>Caso_BrandSpecialist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_CustomerCare__c</fullName>
        <label>Caso_CustomerCare</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_OMS__c</fullName>
        <label>Caso_OMS</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambioStore__c</fullName>
        <label>Caso_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambio__c</fullName>
        <label>Caso_ResoCambio</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_ResoCambioStore__c</fullName>
        <label>Task_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Wishlist__c</fullName>
        <label>Task_Wishlist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Reso_Cambio_in_Store</fullName>
        <active>true</active>
        <description>Reso/Cambio in Store</description>
        <label>Reso/Cambio in Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Wishlist</fullName>
        <active>true</active>
        <description>Wishlist</description>
        <label>Wishlist</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <label>Id Cliente DW</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestCaseTest.cls
@isTest
private class RestCaseTest {
    
    
    @isTest static void test_post() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            req.requestURI =    '/Ticket_v1.0/'; 
            req.httpMethod = 'POST';
            //req.requestBody = Blob.valueof('{  "customer" :{"LastName": "Brambilla"}');
            
            //String recordTypeID = DescribeUtils.getRecordTypeId('Case', 'Customer Care');
            RecordTypeSetting__c rst = new RecordTypeSetting__c(Name='General');
            rst.Caso_ResoCambio__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio');
            rst.Caso_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio_in_Store');
            rst.Caso_CustomerCare__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce');
            rst.Caso_BrandSpecialist__c = DescribeUtils.getRecordTypeId('Case', 'Brand_Specialist');
            rst.Caso_OMS__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_OMS');
            rst.Task_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Task', 'Reso_Cambio_in_Store');
            rst.Task_Wishlist__c = DescribeUtils.getRecordTypeId('Task', 'Wishlist');
            rst.Caso_NotifyMe__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce_Notify_Me');
            insert rst;
            
            Location__c l = new Location__c();
            l.Id_Location_Micros__c = '123456789';
            l.Id_Location__c = '123456789';
            insert l;
            
            Account a = new Account(
                FirstName = 'name', 
                LastName = 'ln', 
                PersonEmail = 'asd@asd.asd',
                Id_Cliente_DW__c = '123456789'
            );
            insert a;
            
            Transaction__c t = new Transaction__c();
            t.Account__c = a.Id;
            t.Name = '123456789';
            insert t;
            
            Transaction_Detail__c td = new Transaction_Detail__c();
            td.Transaction__c = t.Id;
            td.Name = '123456789';
            insert td;
            
            Product__c p = new Product__c();
            p.Item_ID__c = '123456789';
            insert p;
            
            Case c = new Case();
            c.Id_Cliente__c = '123456789';
            c.Origine_Ticket__c = 'ResoCambio';
            c.Tipologia__c = 'E';
            c.id_Store__c = '123456789';
            c.Id_Ordine__c = '123456789';
            c.Id_Reso__c = '123456789';
            
            Case c1 = new Case();
            c1.Id_Cliente__c = '123456789';
            c1.Origine_Ticket__c = 'ResoCambio';
            c1.Tipologia__c = 'E';
            c1.id_Store__c = 'asd';
            c1.Id_Ordine__c = '123456789';
            c1.Id_Reso__c = '123456789';
            
            Case c1a = new Case();
            c1a.Id_Cliente__c = '123456789';
            c1a.Origine_Ticket__c = 'asd';
            c1a.Tipologia__c = 'E';
            c1a.id_Store__c = 'asd';
            c1a.Id_Ordine__c = '123456789';
            c1a.Id_Reso__c = '123456789';
            
            Case c2 = new Case();
            c2.Id_Cliente__c = '123456789';
            c2.Origine_Ticket__c = 'ResoCambio';
            c2.Tipologia__c = 'E';
            c2.id_Store__c = '123456789';
            c2.Id_Ordine__c = 'asd';
            c2.Id_Reso__c = '123456789';
            
            Case c3 = new Case();
            c3.Id_Cliente__c = '123456789';
            c3.Origine_Ticket__c = 'ResoCambio';
            c3.Tipologia__c = 'E';
            c3.id_Store__c = '123456789';
            c3.Id_Ordine__c = '123456789';
            c3.Id_Reso__c = 'asd';
            
            Case c3a = new Case();
            c3a.Id_Cliente__c = 'asd';
            c3a.Origine_Ticket__c = 'ResoCambio';
            c3a.Tipologia__c = 'E';
            c3a.id_Store__c = '123456789';
            c3a.Id_Ordine__c = '123456789';
            c3a.Id_Reso__c = '123456789';
            
            Case c4 = new Case();
            c4.Id_Cliente__c = '123456789';
            c4.Origine_Ticket__c = 'ResoCambioStore';
            c4.Tipologia__c = 'E';
            c4.id_Store__c = '123456789';
            c4.Id_Ordine__c = '123456789';
            c4.Id_Reso__c = '123456789';
            
            
            Case c5 = new Case();
            c5.Id_Cliente__c = '123456789';
            c5.Origine_Ticket__c = 'CustomerCare';
            c5.Tipologia__c = 'E';
            c5.id_Store__c = '123456789';
            c5.Id_Ordine__c = '123456789';
            c5.Id_Reso__c = '123456789';
            
            
            Case c6 = new Case();
            c6.Id_Cliente__c = '123456789';
            c6.Origine_Ticket__c = 'BrandSpecialist';
            c6.Tipologia__c = 'E';
            c6.id_Store__c = '123456789';
            c6.Id_Ordine__c = '123456789';
            c6.Id_Reso__c = '123456789';
            c6.Prodotto_Selezionato__c = '123456789';
            
            
            Case c6a = new Case();
            c6a.Id_Cliente__c = '123456789';
            c6a.Origine_Ticket__c = 'BrandSpecialist';
            c6a.Tipologia__c = 'E';
            c6a.id_Store__c = '123456789';
            c6a.Id_Ordine__c = '123456789';
            c6a.Id_Reso__c = '123456789';
            c6a.Prodotto_Selezionato__c = 'asd';
            
            
            Case c7 = new Case();
            c7.Id_Cliente__c = '123456789';
            c7.Origine_Ticket__c = 'OMS';
            c7.Tipologia__c = 'E';
            c7.id_Store__c = '123456789';
            c7.Id_Ordine__c = '123456789';
            c7.Id_Reso__c = '123456789';
            
            
            //c.RecordTypeId = recordTypeID;
            
            RestContext.response= res;
            RestContext.request = req;
            
            RestCase.doPost(c);
            RestCase.doPost(c1);
            RestCase.doPost(c1a);
            RestCase.doPost(c2);
            RestCase.doPost(c3);
            RestCase.doPost(c3a);
            RestCase.doPost(c4);
            RestCase.doPost(c5);
            RestCase.doPost(c6);
            RestCase.doPost(c6a);
            RestCase.doPost(c7);
            
            RestCase.RestCaseHandler rch = new RestCase.RestCaseHandler();
            //rch.get(req,res);
            //rch.beforeUpdate(req,res, null);
            //rch.afterUpdateResponse(req,res, null);
            
            
        }
        Test.stopTest();
        
    }
    
    @isTest static void test_put() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            
            req.httpMethod = 'PUT';
            //req.requestBody = Blob.valueof('{  "customer" :{"LastName": "Brambilla"}');
            
            //String recordTypeID = DescribeUtils.getRecordTypeId('Case', 'Customer Care');
            RecordTypeSetting__c rst = new RecordTypeSetting__c(Name='General');
            rst.Caso_ResoCambio__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio');
            rst.Caso_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio_in_Store');
            rst.Caso_CustomerCare__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce');
            rst.Caso_BrandSpecialist__c = DescribeUtils.getRecordTypeId('Case', 'Brand_Specialist');
            rst.Caso_OMS__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_OMS');
            rst.Task_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Task', 'Reso_Cambio_in_Store');
            rst.Task_Wishlist__c = DescribeUtils.getRecordTypeId('Task', 'Wishlist');
            rst.Caso_NotifyMe__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce_Notify_Me');
            insert rst;
            
            Location__c l = new Location__c();
            l.Id_Location_Micros__c = '123456789';
            l.Id_Location__c = '123456789';
            insert l;
            
            Account a = new Account(
                FirstName = 'name', 
                LastName = 'ln', 
                PersonEmail = 'asd@asd.asd',
                Id_Cliente_DW__c = '123456789'
            );
            insert a;
            
            Transaction__c t = new Transaction__c();
            t.Account__c = a.Id;
            t.Name = '123456789';
            insert t;
            
            Transaction_Detail__c td = new Transaction_Detail__c();
            td.Transaction__c = t.Id;
            td.Name = '123456789';
            insert td;
            
            Product__c p = new Product__c();
            p.Item_ID__c = '123456789';
            insert p;
            
            Case c = new Case();
            c.Id_Cliente__c = '123456789';
            c.Origine_Ticket__c = 'ResoCambio';
            c.Tipologia__c = 'E';
            c.id_Store__c = '123456789';
            c.Id_Ordine__c = '123456789';
            c.Id_Reso__c = '123456789';
            insert c;
            
            
            
            //c.RecordTypeId = recordTypeID;
            req.requestURI =    '/Ticket_v1.0/'+c.Id;
            RestContext.response= res;
            RestContext.request = req;
            
            RestCase.doPatch(c);
            
            
            RestCase.RestCaseHandler rch = new RestCase.RestCaseHandler();
            rch.get(req,res);
            rch.beforeUpdate(req,res, c);
            rch.afterUpdateResponse(req,res, c);
            
            
        }
        Test.stopTest();
        
    }
    @isTest static void test_get() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            
            req.httpMethod = 'GET';
            //req.requestBody = Blob.valueof('{  "customer" :{"LastName": "Brambilla"}');
            
            //String recordTypeID = DescribeUtils.getRecordTypeId('Case', 'Customer Care');
            RecordTypeSetting__c rst = new RecordTypeSetting__c(Name='General');
            rst.Caso_ResoCambio__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio');
            rst.Caso_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio_in_Store');
            rst.Caso_CustomerCare__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce');
            rst.Caso_BrandSpecialist__c = DescribeUtils.getRecordTypeId('Case', 'Brand_Specialist');
            rst.Caso_OMS__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_OMS');
            rst.Task_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Task', 'Reso_Cambio_in_Store');
            rst.Task_Wishlist__c = DescribeUtils.getRecordTypeId('Task', 'Wishlist');
            rst.Caso_NotifyMe__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce_Notify_Me');
            insert rst;
            
            Location__c l = new Location__c();
            l.Id_Location_Micros__c = '123456789';
            l.Id_Location__c = '123456789';
            insert l;
            
            Account a = new Account(
                FirstName = 'name', 
                LastName = 'ln', 
                PersonEmail = 'asd@asd.asd',
                Id_Cliente_DW__c = '123456789'
            );
            insert a;
            
            Transaction__c t = new Transaction__c();
            t.Account__c = a.Id;
            t.Name = '123456789';
            insert t;
            
            Transaction_Detail__c td = new Transaction_Detail__c();
            td.Transaction__c = t.Id;
            td.Name = '123456789';
            insert td;
            
            Product__c p = new Product__c();
            p.Item_ID__c = '123456789';
            insert p;
            
            Case c = new Case();
            c.Id_Cliente__c = '123456789';
            c.Origine_Ticket__c = 'ResoCambio';
            c.Tipologia__c = 'E';
            c.id_Store__c = '123456789';
            c.Id_Ordine__c = '123456789';
            c.Id_Reso__c = '123456789';
            insert c;
            
            
            
            //c.RecordTypeId = recordTypeID;
            req.requestURI =    '/Ticket_v1.0/'+c.Id;
            RestContext.response= res;
            RestContext.request = req;
            
            RestCase.doGet();
            
            
            RestCase.RestCaseHandler rch = new RestCase.RestCaseHandler();
            rch.get(req,res);
            
            
            
        }
        Test.stopTest();
        
    }
    
}