src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Id_Associate__c</fullName>
        <label>Id Associate</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location__c</fullName>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Activity_tracking__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>Out of store</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Activity tracking</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Activity Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity tracking</pluralLabel>
    <recordTypes>
        <fullName>Mailing</fullName>
        <active>true</active>
        <label>Mailing</label>
    </recordTypes>
    <recordTypes>
        <fullName>One_To_One</fullName>
        <active>true</active>
        <label>One2One</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Associated__c.object
<CustomObject>
    <description>Anagrafiche venditori negozi (collegato a Store di riferimento)</description>
    <fields>
        <fullName>Id_Associate__c</fullName>
        <label>Id Associate</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Associateds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <fields>
        <fullName>Id_Location__c</fullName>
        <externalId>true</externalId>
        <label>Id Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Id_Associate__c</fullName>
        <label>Id Associate</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Profile</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Codice_Associate__c</fullName>
        <label>Codice Associate</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codice_Boutique__c</fullName>
        <label>Codice Boutique</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateActivityTrackingControllerTest.cls
@isTest
public class CreateActivityTrackingControllerTest {

	@isTest static void testGetLabels(){
		CreateActivityTrackingController.getLabels();
	}

	@isTest static void testGetCategorie(){
		CreateActivityTrackingController.getCategorie();
	}

	@isTest static void testGetRecordTypes(){
		CreateActivityTrackingController.getRecordTypes();
	}

	@isTest static void testGetSelectedCustomer(){
		try{

			CreateActivityTrackingController.getSelectedCustomer('("asdasd")');
		}
		catch(Exception e) {

		}

		User usr = AllDataFactory.create_User();
		insert usr;

		Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
		insert profileSettings;

		// Test.startTest();
		Account a;
		System.runAs(usr){

			a = AllDataFactory.create_PersonAccount_Birthday();
			insert a;
		}
		Test.startTest();
		CreateActivityTrackingController.getSelectedCustomer(a.Id);
		Test.stopTest();
	}

	@isTest static void testCreateNewActivityTracking(){

		User usr = AllDataFactory.create_User();
		insert usr;

		Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
		insert profileSettings;

		// Test.startTest();
		Account a;
		System.runAs(usr){

			try{

				CreateActivityTrackingController.createNewActivityTracking(null);
			}
			catch(Exception e) {

			}

			// User usr = AllDataFactory.create_User();
			// insert usr;

			// Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
			// insert profileSettings;

			// // Test.startTest();
			// Account a;
			// System.runAs(usr){

			//  a = AllDataFactory.create_PersonAccount_Birthday();
			//  insert a;
			// }

			Activity_Tracking__c at1 = AllDataFactory.create_Activity_Tracking('One_To_One');
			Activity_Tracking__c at2 = AllDataFactory.create_Activity_Tracking('Mailing');
			Test.startTest();
			CreateActivityTrackingController.createNewActivityTracking(at1);


			CreateActivityTrackingController.createNewActivityTracking(at2);
			Test.stopTest();
		}

	}

	@isTest static void getUserInfo(){
		User usr = AllDataFactory.create_User();
		usr.Codice_Associate__c = 'codiceAss';
		usr.Codice_Boutique__c = 'codiceBout';
		insert usr;

		Location__c location = new Location__c(Id_Location__c = 'codiceBout', Name = 'test');
		insert location;

		Associated__c associate = new Associated__c(Id_Associate__c = 'codiceAss', Name = 'test', Location__c= location.Id);
		insert associate;		

		System.runAs(usr){
			CreateActivityTrackingController.getUserInfo();
		}
	}
}