src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Privacy3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consenso profilazione</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Activity_tracking__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Activity category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Activity_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Out_of_store__c</fullName>
        <label>Where (out of store)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Instore</fullName>
                </value>
                <value>
                    <fullName>Out of store</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Activity tracking</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Activity Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity tracking</pluralLabel>
    <recordTypes>
        <fullName>One_To_One</fullName>
        <active>true</active>
        <label>One2One</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Account personale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchOnCampaignClosed.cls
@isTest
private class TestBatchOnCampaignClosed {
 
    
       // List<Activity_tracking__c> ListOfActivityTrackings = new List<Activity_tracking__c>();
        List<Campaign> ListOfCampaignMembers = new List<Campaign>();
    	       


 	static testmethod void test()
    {
        
        
         String personAccountRecordTypeId =  Account.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
         Account acc = new Account(
            FirstName = 'TestName',
            LastName = 'TestSurname',
            Sesso__c = 'M',
            PersonEmail =  'personalEmail@gmail.com',
            Phone = '12345679',
            PersonMobilePhone = '16844838',
            RecordTypeId = personAccountRecordTypeId,
            Privacy3__c = true,
            PersonBirthdate = Date.Today().addDays(1)
            );
			//insert acc;
        
         Account acc1 = new Account(
            FirstName = 'TestName1',
            LastName = 'TestSurname1',
            Sesso__c = 'M',
            PersonEmail =  'personal1Email@gmail.com',
            Phone = '123456791',
            PersonMobilePhone = '168448381',
            RecordTypeId = personAccountRecordTypeId,
            Privacy3__c = true,
            PersonBirthdate = Date.Today().addDays(1)
            );
			//insert acc1;
         
         String CampaignRecordType =  Campaign.SobjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('One_To_One').getRecordTypeId();
         Campaign c = new Campaign(
            Name = 'Campaign a',
            Quantity__c = '1',
            Email__c = true,
            RecordTypeId = CampaignRecordType,
            Categoria__c = 'OT_Tour Visit',
            Location__c = 'Out of store',
            Location_Out_of_store__c = 'aaa',
            StartDate = Date.Today().addDays(-1),
            EndDate = Date.Today().addDays(1)
            );
            insert c;


            Contact cont = new Contact( LastName = 'LastName' , AccountId = acc.Id  );
            insert cont;
                                        
            Contact cont1 = new Contact( LastName = 'LastName1', AccountId = acc1.Id  );
            insert cont1;
            

            CampaignMember cm = new CampaignMember(
            CampaignId = c.Id,
            ContactId = cont.Id
            );
           // insert cm;

            CampaignMember cm1 = new CampaignMember(
            CampaignId = c.Id,
            ContactId = cont1.Id
            );
           // insert cm1;


        List<CampaignMember> ListOfCampaignMembers = new List<CampaignMember>();
        ListOfCampaignMembers.add(cm);
        ListOfCampaignMembers.add(cm1); 
        insert ListOfCampaignMembers;

        List<Campaign> ListOfCampaigns = new List<Campaign>();
        ListOfCampaigns.add(c);
        List<String> EmptyListOfCampaignIds = new List<String>();
        List<String> ListOfCampaignIds = new List<String>();

        for(Campaign ca : ListOfCampaigns)
        {
           ListOfCampaignIds.add((String)ca.Id);
        }
        //insert ListOfCampaigns;
        //insert ListOfCampaignIds;
    
    
   
           
		
		Test.startTest();
        
        	        
        	
			BatchActivityTrackingOnCampaignClosed uca = new BatchActivityTrackingOnCampaignClosed(ListOfCampaignIds);
        	Id batchId = Database.executeBatch(uca);	
        
        	
			BatchActivityTrackingOnCampaignClosed uca1 = new BatchActivityTrackingOnCampaignClosed(EmptyListOfCampaignIds);
        	Id batchId1 = Database.executeBatch(uca1);

			//Id batchInstanceId = Database.executeBatch(new BatchActivityTrackingOnCampaignClosed(ListOfCampaignIds), 3);


     
           
        Test.stopTest();
    }
       
    
}