src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Once the boutique is allocated the preferred client advisor is defined considering both amount and recency of purchases, as above</inlineHelpText>
        <label>Allocated Client Advisor</label>
        <referenceTo>Associated__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Marketing_Y_N__c</fullName>
        <formula>IF ( OR( Privacy1__c = true, Privacy2__c = true), true,
IF (AND (Privacy_1__c = true,Privacy1__c = false,Privacy2__c = false,ISBLANK(Data_Ultimo_Aggiornamento_Privacy__c)) 
     , true, false ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Marketing Y/N</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posta__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Postal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Privacy3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consenso profilazione</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Titolare_Client_Advisor_Boutique__c</fullName>
        <formula>IF ( $User.ProfileId =  $Setup.Profile__c.Id_Associate__c,
     IF (AND (Id_Associate__c = $User.Codice_Associate__c, !ISNULL(Id_Associate__c)) , true, false),
     IF ($User.ProfileId =  $Setup.Profile__c.Id_Boutique__c,
         IF (AND (Id_Location__c = $User.Codice_Boutique__c, !ISNULL(Id_Location__c)) , true, false),false))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Titolare Client Advisor / Boutique</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associated__c.object
<CustomObject>
    <description>Anagrafiche venditori negozi (collegato a Store di riferimento)</description>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HomeBirthdayNoAssociateController.cls
public class HomeBirthdayNoAssociateController {

	@AuraEnabled
	public static Map<String,String> getLabels(){
		Map<String,String> labels = new Map<String,String>();
		try{

			Map<String, Schema.SObjectField> fields = Account.SObjectType.getDescribe().fields.getMap();
			for(String fieldName : fields.keySet()) {
				labels.put(fieldName,fields.get(fieldName).getDescribe().getLabel());
			}
			return labels;
		}
		catch(Exception e) {
			system.debug('problems to get fields');
			return new Map<String,String>();
		}

	}

	@AuraEnabled
	public static Integer getTotalCount(){
		AggregateResult results;
		// List<CampaignMember> myActiveCampaignMembers = new List<CampaignMember>();
		// Set<String> campaignsId = new Set<String>();
		Integer total = 0;
		// myActiveCampaignMembers = [
		//  SELECT Id,CampaignId
		//  FROM CampaignMember
		//  WHERE (Titolare_Client_Advisor_Boutique__c = true)
		// ];

		// if(myActiveCampaignMembers != null && myActiveCampaignMembers.size() > 0) {
		//  for(CampaignMember cm : myActiveCampaignMembers) {
		//      campaignsId.add(cm.CampaignId);
		//  }
		// if(campaignsId != null && campaignsId.size() > 0) {
		try{
			results = [
				SELECT count(Id) total
				FROM Account
				WHERE (IsPersonAccount = true AND PersonBirthdate = NEXT_N_DAYS:30 AND Titolare_Client_Advisor_Boutique__c = true)
			];
		}
		catch(Exception e) {
			total = 0;
		}

		total =(Integer)results.get('total');
		//  }
		// }
		if(results != null)
			return total;
		else
			return 0;

	}

	@AuraEnabled
	public static List<Account> getBirthdays(Integer limits, Integer offsets){
		System.debug('limits'+limits);
		System.debug('offsets'+offsets);
		Integer intlimits = integer.valueof(limits);
		Integer intoffsets = integer.valueof(offsets);
		// List<Campaign> myActiveCampaigns = new List<Campaign>();
		// List<CampaignMember> myActiveCampaignMembers = new List<CampaignMember>();
		// Set<String> campaignsId = new Set<String>();
		// myActiveCampaignMembers = [
		//  SELECT Id,CampaignId
		//  FROM CampaignMember
		//  WHERE (Titolare_Client_Advisor_Boutique__c = true)
		// ];

		// if(myActiveCampaignMembers != null && myActiveCampaignMembers.size() > 0) {
		// for(CampaignMember cm : myActiveCampaignMembers) {
		//  campaignsId.add(cm.CampaignId);
		// }
		// if(campaignsId != null && campaignsId.size() > 0) {
		List<Account> birthdays = [
			SELECT Id,Name,PersonBirthdate,Marketing_Y_N__c,Posta__c,Email__c,Telefono__c,Privacy3__c,Associate__r.Name
			FROM Account
			WHERE (IsPersonAccount = true AND PersonBirthdate = NEXT_N_DAYS:30 AND Titolare_Client_Advisor_Boutique__c = true)
			ORDER BY PersonBirthdate ASC NULLS LAST
			LIMIT :intlimits
			OFFSET :intoffsets
		];
		// }
		// }
		if(birthdays != null && birthdays.size() > 0)
			return birthdays;
		else
			return new List<Account>();

	}

}