src/objects/Account_Misure_Sartoriali__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Schede_Misura_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheda Misure Sartoria Solomeo</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Nome Scheda Misura Sartoria Solomeo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schede Misure Sartoria Solomeo</pluralLabel>
    <recordTypes>
        <fullName>Pantalone</fullName>
        <active>true</active>
        <label>Pantalone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Capo__c.object
<CustomObject>
    <fields>
        <fullName>Codice_Abito__c</fullName>
        <label>Codice Abito</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codice_Giacca__c</fullName>
        <label>Codice Giacca</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codice_Pantalone__c</fullName>
        <label>Codice Pantalone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Modello_Giacca__c</fullName>
        <label>Descrizione Modello Giacca</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAVALLO REVER GRANDE</fullName>
                </value>
                <value>
                    <fullName>REVER A LANCIA</fullName>
                </value>
                <value>
                    <fullName>REVER A LANCIA GRANDE</fullName>
                </value>
                <value>
                    <fullName>REVER A SPECCHIO 3 TASCHE A TOPPA</fullName>
                </value>
                <value>
                    <fullName>TRADIZIONALE</fullName>
                </value>
                <value>
                    <fullName>UN PETTO E MEZZO</fullName>
                </value>
                <value>
                    <fullName>UN PETTO E MEZZO TASCHE A TOPPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Descrizione_Modello_Pantalone__c</fullName>
        <label>Descrizione Modello Pantalone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flat Fondo 19,5</fullName>
                </value>
                <value>
                    <fullName>Pince Fondo 19,5</fullName>
                </value>
                <value>
                    <fullName>Flat with 19,5 cm bottom</fullName>
                </value>
                <value>
                    <fullName>Pleated with 19,5 cm bottom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modello_Giacca__c</fullName>
        <label>Modello Giacca</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stagione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stagione</label>
        <referenceTo>Stagione__c</referenceTo>
        <relationshipLabel>Capi</relationshipLabel>
        <relationshipName>Capi</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Capo</label>
    <nameField>
        <label>Capo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Capi</pluralLabel>
    <recordTypes>
        <fullName>Pantalone</fullName>
        <active>true</active>
        <label>Pantalone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Capo_Tessuto__c.object
<CustomObject>
    <fields>
        <fullName>Capo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capo</label>
        <referenceTo>Capo__c</referenceTo>
        <relationshipName>Tessuti_Capi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codice_Giacca__c</fullName>
        <formula>Capo__r.Codice_Giacca__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codice Giacca</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codice_Pantalone__c</fullName>
        <formula>Capo__r.Codice_Pantalone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codice Pantalone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Modello_Giacca__c</fullName>
        <formula>text(Capo__r.Descrizione_Modello_Giacca__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descrizione Modello Giacca</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Modello_Pantalone__c</fullName>
        <formula>text(Capo__r.Descrizione_Modello_Pantalone__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descrizione Modello Pantalone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tessuto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tessuto</label>
        <referenceTo>Tessuto__c</referenceTo>
        <relationshipName>Tessuti_Capi</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Capo - Tessuto</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Capo - Tessuto Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capi - Tessuti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fodera__c.object
<CustomObject>
    <fields>
        <fullName>Codice__c</fullName>
        <label>Codice</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Fodera</label>
    <nameField>
        <label>Fodera Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fodere</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ordine_Sartoria_Solomeo__c.object
<CustomObject>
    <fields>
        <fullName>Capo_Tessuto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capo - Tessuto</label>
        <referenceTo>Capo_Tessuto__c</referenceTo>
        <relationshipLabel>Ordini Sartoria Solomeo</relationshipLabel>
        <relationshipName>Ordini_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capo</label>
        <referenceTo>Capo__c</referenceTo>
        <relationshipLabel>Ordini Sartoria Solomeo</relationshipLabel>
        <relationshipName>Ordini_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descrizione_Colore__c</fullName>
        <formula>text(Tessuto_Colore__r.Descrizione_Colore__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descrizione Colore</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Tessuto__c</fullName>
        <formula>Tessuto__r.Descrizione_Tessuto__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descrizione Tessuto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tessuto_Colore__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tessuto Colore</label>
        <referenceTo>Tessuto_Colore__c</referenceTo>
        <relationshipLabel>Ordini Sartoria Solomeo</relationshipLabel>
        <relationshipName>Ordini_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tessuto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tessuto</label>
        <referenceTo>Tessuto__c</referenceTo>
        <relationshipLabel>Ordini Sartoria Solomeo</relationshipLabel>
        <relationshipName>Ordini_Sartoria_Solomeo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ordine Sartoria Solomeo</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Nome Ordine Sartoria Solomeo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordini Sartoria Solomeo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stagione__c.object
<CustomObject>
    <description>Stagione MTM</description>
    <fields>
        <fullName>Attiva__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attiva</label>
        <type>Checkbox</type>
    </fields>
    <label>Stagione</label>
    <nameField>
        <label>Stagione Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stagioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tessuto__c.object
<CustomObject>
    <fields>
        <fullName>Codice__c</fullName>
        <label>Codice</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Tessuto__c</fullName>
        <label>Descrizione Tessuto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Peso__c</fullName>
        <label>Peso</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipologia_Tessuto__c</fullName>
        <label>Tipologia Tessuto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tessuto</label>
    <nameField>
        <label>Tessuto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tessuti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tessuto_Colore__c.object
<CustomObject>
    <fields>
        <fullName>Codice_Colore__c</fullName>
        <label>Codice Colore</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione_Tessuto__c</fullName>
        <formula>Tessuto__r.Descrizione_Tessuto__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descrizione Tessuto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stagione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stagione</label>
        <referenceTo>Stagione__c</referenceTo>
        <relationshipLabel>Tessuti - Colori</relationshipLabel>
        <relationshipName>Tessuti_Colori</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tessuto__c</fullName>
        <label>Tessuto</label>
        <referenceTo>Tessuto__c</referenceTo>
        <relationshipLabel>Tessuti - Colori</relationshipLabel>
        <relationshipName>Tessuti_Colori</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tessuto - Colore</label>
    <nameField>
        <label>Tessuto - Colore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tessuti - Colori</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Codice_Boutique__c</fullName>
        <label>Codice Boutique</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Rest_MTM_CollectionsPerformantTest.cls
@isTest
public class Rest_MTM_CollectionsPerformantTest {
    
    @isTest static void test_Get(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User u = AllDataFactory.create_User();
        u.Codice_Boutique__c = '001';
        insert u;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(u.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        system.runAs(u){
            Account acc = AllDataFactory.create_Account();
            insert acc;
            
            List<Account_Misure_Sartoriali__c> listAms = new List<Account_Misure_Sartoriali__c>();
            Account_Misure_Sartoriali__c ams = AllDataFactory.create_Account_Misure_Sartoriali();
            ams.Account__c = acc.Id;
            insert ams;
            listAms.add(ams);
            
            Account_Misure_Sartoriali__c ams1 = AllDataFactory.create_Account_Misure_Sartoriali();
            ams1.Account__c = acc.Id;
            insert ams1;
            listAms.add(ams1);
            Stagione__c st = new Stagione__c();
            st.Name = 'test';
            st.Attiva__c = true;
            insert st;
            
            Capo__c capo = new Capo__c();
            capo.Stagione__c = st.Id;
            capo.Name = 'Test Name';
            capo.Codice_Abito__c = '33';
            capo.Codice_Giacca__c = '2332';
            capo.Codice_Pantalone__c = '232';
            capo.Descrizione_Modello_Giacca__c = '23';
            capo.Descrizione_Modello_Pantalone__c = '23';
            capo.Modello_Giacca__c = '32';
            
            insert capo;
            
            
            
            Tessuto__c tes = new Tessuto__c();
            tes.Name = 'ts Name';
            tes.Codice__c = '2323';
            tes.Descrizione_Tessuto__c ='sagfs';
            tes.Peso__c ='32';
            tes.Tipologia_Tessuto__c ='232' ;
            insert tes;
            
            Capo_Tessuto__c capoTe = new Capo_Tessuto__c();
            capoTe.Capo__c = capo.Id;
            capoTe.Tessuto__c = tes.Id;
            insert capoTe;
            Tessuto_Colore__c col = new Tessuto_Colore__c();
            
            col.Tessuto__c =tes.Id;
            col.Name = 'Test colore';
            col.Codice_Colore__c = 'Fw222';
            col.Descrizione_Colore__c = 'blue ';
            insert col;
            
            Fodera__c fd = new Fodera__c();
            fd.Name = 'Test Fd';
            fd.Codice__c = '32e23';
            fd.Descrizione__c = '2efds';         
            insert fd;
            
            Location__c c = new Location__c();
            insert c;
            
            Misure_di_Riferimento_Sartoria__c mdrs =  AllDataFactory.create_Misure_di_Riferimento_Sartoria('Pantalone');
            
            
            Associated__c t = new Associated__c();
            t.Id_Associate_Micros__c = '123456789';
            t.Location__c = c.Id;
            insert t;
            List<Ordine_Sartoria_Solomeo__c> listOss = new List<Ordine_Sartoria_Solomeo__c>();
            Ordine_Sartoria_Solomeo__c oss = new Ordine_Sartoria_Solomeo__c();
            oss.Associate__c = t.id;
            oss.Cliente__c = acc.Id;
            //oss.Name = 'Test';
            insert oss;
            listOss.add(oss);
            //Rest_MTM_Collections_Performant2.CollectionWrapper cW = new Rest_MTM_Collections.CollectionWrapper();
            //MC- To test Rest_MTM_Collections_Performant
            //Rest_MTM_Collections_Performant2.CollectionWrapper cW1 = new Rest_MTM_Collections_Performant.CollectionWrapper();
            
            Id recordTypeId = Schema.SObjectType.Misure_di_Riferimento_Sartoria__c.getRecordTypeInfosByName().get('Pantalone').getRecordTypeId();
            
            req.requestURI =    '/MTM/V2/Collections/'; 
            req.httpMethod = 'GET';
            
            RestContext.response= res;
            RestContext.request = req;
            
            Object rw = Rest_MTM_Collections_Performant2.doGet();
            //MC- To test Rest_MTM_Collections_Performant
            Object rw1 = Rest_MTM_Collections_Performant2.doGet();
            
            req.requestURI = '/MTM/V2/Collections/' + capo.Id;
            RestContext.request = req;
            rw1 = Rest_MTM_Collections_Performant2.doGet();
            
            Object rw2 = Rest_MTM_Collections_Performant2.doGet();
            
            req.requestURI = '/MTM/V2/Collections/'+recordTypeId+'__Sera' ;
            RestContext.request = req;
            rw2 = Rest_MTM_Collections_Performant2.doGet();
            
            Object rw3 = Rest_MTM_Collections_Performant2.doGet();
            
            req.requestURI = '/MTM/V2/Collections/'+col.Id ;
            RestContext.request = req;
            rw3 = Rest_MTM_Collections_Performant2.doGet(); 
        }
        Test.stopTest();
        
    }
    
    @isTest static void test_get1() {
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().beforeUpdate(null, null, null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().afterUpdateResponse(null, null, null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().beforeInsert(null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().afterInsert(null);
        //MC- To test Rest_MTM_Collections_Performant
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().beforeUpdate(null, null, null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().afterUpdateResponse(null, null, null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().beforeInsert(null);
        new Rest_MTM_Collections_Performant2.RestCollectionsHandler().afterInsert(null);
    }
}