src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Data_Primo_Acquisto_E_commerce__c</fullName>
        <label>Data primo acquisto E-commerce</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Primo_Acquisto__c</fullName>
        <label>Data Primo acquisto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Ultimo_Acquisto__c</fullName>
        <label>Data ultimo acquisto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_ultimo_acquisto_E_commerce__c</fullName>
        <label>Data ultimo acquisto E-commerce</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_BRL__c</fullName>
        <label>Importo Acquisti E-commerce BRL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_CAD__c</fullName>
        <label>Importo Acquisti E-commerce CAD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_CHF__c</fullName>
        <label>Importo Acquisti E-commerce CHF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_CNY__c</fullName>
        <label>Importo Acquisti E-commerce CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_EUR__c</fullName>
        <label>Importo Acquisti E-commerce EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_GBP__c</fullName>
        <label>Importo Acquisti E-commerce GBP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_HKD__c</fullName>
        <label>Importo Acquisti E-commerce HKD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce_JPY__c</fullName>
        <label>Importo Acquisti E-commerce JPY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_E_commerce__c</fullName>
        <label>Importo Acquisti E-commerce (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_ultimi_6_12_mesi__c</fullName>
        <label>Importo Acquisti ultimi 6-12 mesi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Acquisti_ultimi_6_mesi__c</fullName>
        <label>Importo Acquisti ultimi 6 mesi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_BPS__c</fullName>
        <label>Importo Totale Acquisti BPS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_BRL__c</fullName>
        <label>Importo Acquisti BRL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_CAD__c</fullName>
        <label>Importo Acquisti CAD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_CHF__c</fullName>
        <label>Importo Acquisti CHF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_CNY__c</fullName>
        <label>Importo Acquisti CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_DOS__c</fullName>
        <label>Importo Tot Acquisti DOS ultimi 24 mesi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_EUR__c</fullName>
        <label>Importo Acquisti EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_Ecommerce__c</fullName>
        <label>Importo Totale Acquisti Ecommerce</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_GBP__c</fullName>
        <label>Importo Acquisti GBP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_HKD__c</fullName>
        <label>Importo Acquisti HKD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_JPY__c</fullName>
        <label>Importo Acquisti JPY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti_USD__c</fullName>
        <label>Importo Acquisti USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_Totale_Acquisti__c</fullName>
        <label>Importo acquisti</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_BRL__c</fullName>
        <label>Importo acquisti ultima stagione BRL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_CAD__c</fullName>
        <label>Importo acquisti ultima stagione CAD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_CHF__c</fullName>
        <label>Importo acquisti ultima stagione CHF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_CNY__c</fullName>
        <label>Importo acquisti ultima stagione CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_EUR__c</fullName>
        <label>Importo acquisti ultima stagione EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_GBP__c</fullName>
        <label>Importo acquisti ultima stagione GBP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_HKD__c</fullName>
        <label>Importo acquisti ultima stagione HKD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_JPY__c</fullName>
        <label>Importo acquisti ultima stagione JPY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione_USD__c</fullName>
        <label>Importo acquisti ultima stagione USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultima_stagione__c</fullName>
        <label>Importo acquisti ultima stagione (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultimi_24_mesi__c</fullName>
        <label>Importo acquisti ultimi 24 mesi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Importo_acquisti_ultimi_36_mesi__c</fullName>
        <label>Importo acquisti ultimi 36 mesi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_BRL__c</fullName>
        <label>Importo totale Resi BRL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_CAD__c</fullName>
        <label>Importo totale Resi CAD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_CHF__c</fullName>
        <label>Importo totale Resi CHF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_CNY__c</fullName>
        <label>Importo totale Resi CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_EUR__c</fullName>
        <label>Importo totale Resi EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_GBP__c</fullName>
        <label>Importo totale Resi GBP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_HKD__c</fullName>
        <label>Importo totale Resi HKD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_JPY__c</fullName>
        <label>Importo totale Resi JPY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi_USD__c</fullName>
        <label>Importo totale Resi USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Importo_totale_Resi__c</fullName>
        <label>Importo totale Resi</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>N_Scontrini__c</fullName>
        <label>N° Scontrini</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_Acquisti_ultime_2_stagioni__c</fullName>
        <label>Numero Acquisti ultime 2 stagioni</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_Store_di_acquisto__c</fullName>
        <label>Numero Store di acquisto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_acquisti_con_sconto__c</fullName>
        <label>Numero acquisti con sconto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numero_capi_resi__c</fullName>
        <label>N° capi resi</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_shipping_country__c</fullName>
        <label>Nazione di spedizione preferita</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_BRL__c</fullName>
        <label>Sconto Medio (netto resi) BRL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_CAD__c</fullName>
        <label>Sconto Medio (netto resi) CAD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_CHF__c</fullName>
        <label>Sconto Medio (netto resi) CHF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_CNY__c</fullName>
        <label>Sconto Medio (netto resi) CNY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_EUR__c</fullName>
        <label>Sconto Medio (netto resi) EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_GBP__c</fullName>
        <label>Sconto Medio (netto resi) GBP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_HKD__c</fullName>
        <label>Sconto Medio (netto resi) HKD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_JPY__c</fullName>
        <label>Sconto Medio (netto resi) JPY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio_USD__c</fullName>
        <label>Sconto Medio (netto resi) USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_Medio__c</fullName>
        <label>Sconto medio (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Totale_Pezzi_Acquistati_Ultima_Stagione__c</fullName>
        <label>Totale Pezzi Acquistati Ultima Stagione</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Totale_Pezzi_Acquistati_Ultimi_12_Mesi__c</fullName>
        <label>Totale Pezzi Acquistati Ultimi 12 Mesi</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Totale_Pezzi_Acquistati__c</fullName>
        <label>Totale pezzi acquistati (netto resi)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Schedule_Batch_ResetKPIOnAccount.cls
global with sharing class Schedule_Batch_ResetKPIOnAccount Implements Database.Batchable<SObject>, Database.Stateful, Schedulable{
    public Boolean testMode = false;
    String Query;
    List<Id> accountids = new List<Id>();
    // Query --SELECT Id FROM Account Where Importo_Totale_Acquisti__c != null AND Id Not In (Select Account__c From Transaction__c) 
    
    global Schedule_Batch_ResetKPIOnAccount(){
        Query = 'SELECT Id, '
            +'Preferred_shipping_country__c,'
            +'Data_Primo_Acquisto__c,'
            +'Data_Ultimo_Acquisto__c,'
            +'Importo_Totale_Acquisti__c,'
            +'Importo_Totale_Acquisti_BRL__c,'
            +'Importo_Totale_Acquisti_CAD__c,'
            +'Importo_Totale_Acquisti_CHF__c,'
            +'Importo_Totale_Acquisti_CNY__c,'
            +'Importo_Totale_Acquisti_EUR__c,'
            +'Importo_Totale_Acquisti_GBP__c,'
            +'Importo_Totale_Acquisti_HKD__c,'
            +'Importo_Totale_Acquisti_JPY__c,'
            +'Importo_Totale_Acquisti_USD__c,'
            +'N_Scontrini__c,'
            +'Sconto_Medio__c,'
            +'Sconto_Medio_BRL__c,'
            +'Sconto_Medio_CAD__c,'
            +'Sconto_Medio_CHF__c,'
            +'Sconto_Medio_CNY__c,'
            +'Sconto_Medio_EUR__c,'
            +'Sconto_Medio_GBP__c,'
            +'Sconto_Medio_HKD__c,'
            +'Sconto_Medio_JPY__c,'
            +'Sconto_Medio_USD__c,'
            +'Totale_Pezzi_Acquistati__c,'
            +'Numero_capi_resi__c,'
            +'Numero_acquisti_con_sconto__c,'
            +'Numero_Store_di_acquisto__c,'
            +'Importo_totale_Resi__c,'
            +'Importo_totale_Resi_BRL__c,'
            +'Importo_totale_Resi_CAD__c,'
            +'Importo_totale_Resi_CHF__c,'
            +'Importo_totale_Resi_CNY__c,'
            +'Importo_totale_Resi_EUR__c,'
            +'Importo_totale_Resi_GBP__c,'
            +'Importo_totale_Resi_HKD__c,'
            +'Importo_totale_Resi_JPY__c,'
            +'Importo_totale_Resi_USD__c,'
            +'Importo_Acquisti_ultimi_6_mesi__c,'
            +'Importo_Acquisti_ultimi_6_12_mesi__c,'
            +'Importo_acquisti_ultima_stagione__c,'
            +'Importo_acquisti_ultima_stagione_BRL__c,'
            +'Importo_acquisti_ultima_stagione_CAD__c,'
            +'Importo_acquisti_ultima_stagione_CHF__c,'
            +'Importo_acquisti_ultima_stagione_CNY__c,'
            +'Importo_acquisti_ultima_stagione_EUR__c,'
            +'Importo_acquisti_ultima_stagione_GBP__c,'
            +'Importo_acquisti_ultima_stagione_HKD__c,'
            +'Importo_acquisti_ultima_stagione_JPY__c,'
            +'Importo_acquisti_ultima_stagione_USD__c,'
            +'Numero_Acquisti_ultime_2_stagioni__c,'
            +'Importo_Totale_Acquisti_DOS__c,'
            +'Importo_Totale_Acquisti_BPS__c,'
            +'Importo_Totale_Acquisti_Ecommerce__c,'
            +'Totale_Pezzi_Acquistati_Ultimi_12_Mesi__c,'
            +'Totale_Pezzi_Acquistati_Ultima_Stagione__c,'
            +'Importo_acquisti_ultimi_24_mesi__c,'
            +'Importo_acquisti_ultimi_36_mesi__c,'
            +'Data_Primo_Acquisto_E_commerce__c,'
            +'Data_ultimo_acquisto_E_commerce__c,'
            +'Importo_Acquisti_E_commerce__c,'
            +'Importo_Acquisti_E_commerce_BRL__c,'
            +'Importo_Acquisti_E_commerce_CAD__c,'
            +'Importo_Acquisti_E_commerce_CHF__c,'
            +'Importo_Acquisti_E_commerce_CNY__c,'
            +'Importo_Acquisti_E_commerce_EUR__c,'
            +'Importo_Acquisti_E_commerce_GBP__c,'
            +'Importo_Acquisti_E_commerce_HKD__c,'
            +'Importo_Acquisti_E_commerce_JPY__c,'
            +'Importo_Acquisti_E_commerce_USD__c,'
            +'N_Ordini_E_commerce__c,'
            +'Sconto_Medio_E_commerce__c,'
            +'Sconto_Medio_E_commerce_BRL__c,'
            +'Sconto_Medio_E_commerce_CAD__c,'
            +'Sconto_Medio_E_commerce_CHF__c,'
            +'Sconto_Medio_E_commerce_CNY__c,'
            +'Sconto_Medio_E_commerce_EUR__c,'
            +'Sconto_Medio_E_commerce_GBP__c,'
            +'Sconto_Medio_E_commerce_HKD__c,'
            +'Sconto_Medio_E_commerce_JPY__c,'
            +'Sconto_Medio_E_commerce_USD__c,'
            +'Totale_pezzi_acquistati_Ecommerce__c,'
            +'Numero_Capi_Resi_E_commerce__c,'
            +'Numero_acquisti_con_sconto_E_commerce__c,'
            +'Importo_totale_Resi_E_commerce__c,'
            +'Importo_totale_Resi_E_commerce_BRL__c,'
            +'Importo_totale_Resi_E_commerce_CAD__c,'
            +'Importo_totale_Resi_E_commerce_CHF__c,'
            +'Importo_totale_Resi_E_commerce_CNY__c,'
            +'Importo_totale_Resi_E_commerce_EUR__c,'
            +'Importo_totale_Resi_E_commerce_GBP__c,'
            +'Importo_totale_Resi_E_commerce_HKD__c,'
            +'Importo_totale_Resi_E_commerce_JPY__c,'
            +'Importo_totale_Resi_E_commerce_USD__c,'
            +'Importo_acquisti_ultima_stagione_E_comm__c,'
            +'Importo_acquisti_ultima_stg_E_comm_BRL__c,'
            +'Importo_acquisti_ultima_stg_E_comm_CAD__c,'
            +'Importo_acquisti_ultima_stg_E_comm_CHF__c,'
            +'Importo_acquisti_ultima_stg_E_comm_CNY__c,'
            +'Importo_acquisti_ultima_stg_E_comm_EUR__c,'
            +'Importo_acquisti_ultima_stg_E_comm_GBP__c,'
            +'Importo_acquisti_ultima_stg_E_comm_HKD__c,'
            +'Importo_acquisti_ultima_stg_E_comm_JPY__c,'
            +'Importo_acquisti_ultima_stg_E_comm_USD__c '
            +'FROM Account ';
        
    }
    
    global void execute(SchedulableContext SC) {
        if(!this.testMode){
            Schedule_Batch_ResetKPIOnAccount accountsToBeProcessed = new Schedule_Batch_ResetKPIOnAccount();
            ID batchprocessid = Database.executeBatch(accountsToBeProcessed, 100 );     
        }
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        this.Query += this.Testmode ? ' limit 10 ' : ' Where Importo_Totale_Acquisti__c != null AND Id Not In (Select Account__c From Transaction__c) ';
        System.debug('Query: ' + Query);
        return Database.getQueryLocator(Query);
    }
    
    global void execute(Database.BatchableContext BC,List<Account> listAccount){
        System.debug('listAccount: ' + listAccount);
        system.debug('listAccount size : ' + listAccount.size());
        
        for(Account acc : listAccount) {
            accountids.add(acc.Id);
            acc.Preferred_shipping_country__c = 	null;
            acc.Data_Primo_Acquisto__c = 	null;
            acc.Data_Ultimo_Acquisto__c = 	null;
            acc.Importo_Totale_Acquisti__c = 	null;
            acc.Importo_Totale_Acquisti_BRL__c = 	null;
            acc.Importo_Totale_Acquisti_CAD__c = 	null;
            acc.Importo_Totale_Acquisti_CHF__c = 	null;
            acc.Importo_Totale_Acquisti_CNY__c = 	null;
            acc.Importo_Totale_Acquisti_EUR__c = 	null;
            acc.Importo_Totale_Acquisti_GBP__c = 	null;
            acc.Importo_Totale_Acquisti_HKD__c = 	null;
            acc.Importo_Totale_Acquisti_JPY__c = 	null;
            acc.Importo_Totale_Acquisti_USD__c = 	null;
            acc.N_Scontrini__c = 	null;
            acc.Sconto_Medio__c = 	null;
            acc.Sconto_Medio_BRL__c = 	null;
            acc.Sconto_Medio_CAD__c = 	null;
            acc.Sconto_Medio_CHF__c = 	null;
            acc.Sconto_Medio_CNY__c = 	null;
            acc.Sconto_Medio_EUR__c = 	null;
            acc.Sconto_Medio_GBP__c = 	null;
            acc.Sconto_Medio_HKD__c = 	null;
            acc.Sconto_Medio_JPY__c = 	null;
            acc.Sconto_Medio_USD__c = 	null;
            acc.Totale_Pezzi_Acquistati__c = 	null;
            acc.Numero_capi_resi__c = 	null;
            acc.Numero_acquisti_con_sconto__c = 	null;
            acc.Numero_Store_di_acquisto__c = 	null;
            acc.Importo_totale_Resi__c = 	null;
            acc.Importo_totale_Resi_BRL__c = 	null;
            acc.Importo_totale_Resi_CAD__c = 	null;
            acc.Importo_totale_Resi_CHF__c = 	null;
            acc.Importo_totale_Resi_CNY__c = 	null;
            acc.Importo_totale_Resi_EUR__c = 	null;
            acc.Importo_totale_Resi_GBP__c = 	null;
            acc.Importo_totale_Resi_HKD__c = 	null;
            acc.Importo_totale_Resi_JPY__c = 	null;
            acc.Importo_totale_Resi_USD__c = 	null;
            acc.Importo_Acquisti_ultimi_6_mesi__c = 	null;
            acc.Importo_Acquisti_ultimi_6_12_mesi__c = 	null;
            acc.Importo_acquisti_ultima_stagione__c = 	null;
            acc.Importo_acquisti_ultima_stagione_BRL__c = 	null;
            acc.Importo_acquisti_ultima_stagione_CAD__c = 	null;
            acc.Importo_acquisti_ultima_stagione_CHF__c = 	null;
            acc.Importo_acquisti_ultima_stagione_CNY__c = 	null;
            acc.Importo_acquisti_ultima_stagione_EUR__c = 	null;
            acc.Importo_acquisti_ultima_stagione_GBP__c = 	null;
            acc.Importo_acquisti_ultima_stagione_HKD__c = 	null;
            acc.Importo_acquisti_ultima_stagione_JPY__c = 	null;
            acc.Importo_acquisti_ultima_stagione_USD__c = 	null;
            acc.Numero_Acquisti_ultime_2_stagioni__c = 	null;
            acc.Importo_Totale_Acquisti_DOS__c = 	null;
            acc.Importo_Totale_Acquisti_BPS__c = 	null;
            acc.Importo_Totale_Acquisti_Ecommerce__c = 	null;
            acc.Totale_Pezzi_Acquistati_Ultimi_12_Mesi__c = 	null;
            acc.Totale_Pezzi_Acquistati_Ultima_Stagione__c = 	null;
            acc.Importo_acquisti_ultimi_24_mesi__c = 	null;
            acc.Importo_acquisti_ultimi_36_mesi__c = 	null;
            acc.Data_Primo_Acquisto_E_commerce__c = 	null;
            acc.Data_ultimo_acquisto_E_commerce__c = 	null;
            acc.Importo_Acquisti_E_commerce__c = 	null;
            acc.Importo_Acquisti_E_commerce_BRL__c = 	null;
            acc.Importo_Acquisti_E_commerce_CAD__c = 	null;
            acc.Importo_Acquisti_E_commerce_CHF__c = 	null;
            acc.Importo_Acquisti_E_commerce_CNY__c = 	null;
            acc.Importo_Acquisti_E_commerce_EUR__c = 	null;
            acc.Importo_Acquisti_E_commerce_GBP__c = 	null;
            acc.Importo_Acquisti_E_commerce_HKD__c = 	null;
            acc.Importo_Acquisti_E_commerce_JPY__c = 	null;
            acc.Importo_Acquisti_E_commerce_USD__c = 	null;
            acc.N_Ordini_E_commerce__c = 	null;
            acc.Sconto_Medio_E_commerce__c = 	null;
            acc.Sconto_Medio_E_commerce_BRL__c = 	null;
            acc.Sconto_Medio_E_commerce_CAD__c = 	null;
            acc.Sconto_Medio_E_commerce_CHF__c = 	null;
            acc.Sconto_Medio_E_commerce_CNY__c = 	null;
            acc.Sconto_Medio_E_commerce_EUR__c = 	null;
            acc.Sconto_Medio_E_commerce_GBP__c = 	null;
            acc.Sconto_Medio_E_commerce_HKD__c = 	null;
            acc.Sconto_Medio_E_commerce_JPY__c = 	null;
            acc.Sconto_Medio_E_commerce_USD__c = 	null;
            acc.Totale_pezzi_acquistati_Ecommerce__c = 	null;
            acc.Numero_Capi_Resi_E_commerce__c = 	null;
            acc.Numero_acquisti_con_sconto_E_commerce__c = 	null;
            acc.Importo_totale_Resi_E_commerce__c = 	null;
            acc.Importo_totale_Resi_E_commerce_BRL__c = 	null;
            acc.Importo_totale_Resi_E_commerce_CAD__c = 	null;
            acc.Importo_totale_Resi_E_commerce_CHF__c = 	null;
            acc.Importo_totale_Resi_E_commerce_CNY__c = 	null;
            acc.Importo_totale_Resi_E_commerce_EUR__c = 	null;
            acc.Importo_totale_Resi_E_commerce_GBP__c = 	null;
            acc.Importo_totale_Resi_E_commerce_HKD__c = 	null;
            acc.Importo_totale_Resi_E_commerce_JPY__c = 	null;
            acc.Importo_totale_Resi_E_commerce_USD__c = 	null;
            acc.Importo_acquisti_ultima_stagione_E_comm__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_BRL__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_CAD__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_CHF__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_CNY__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_EUR__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_GBP__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_HKD__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_JPY__c = 	null;
            acc.Importo_acquisti_ultima_stg_E_comm_USD__c = 	null;
        }
        
        update listAccount;
        
        
    }
    
    global void finish(Database.BatchableContext BC){
        
        System.debug('BATCH: finish');
        System.debug('Reset KPI on : ' + accountids.size() + ' :  Accounts');
        System.debug('Reset KPI on : ' + accountids + ' :  Accounts');
        System.debug('Reset KPI on : ' + Limits.getHeapSize() + ' :  Heap Size');
    }
}