src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente E-commerce</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente AS400</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Alert_Dati_Ecommerce__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alert Dati E-commerce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citta__c</fullName>
        <formula>Account.PersonMailingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Città</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citta_input__c</fullName>
        <label>Città (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cognome_Cliente__c</fullName>
        <formula>Account.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cognome Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cognome_Cliente_input__c</fullName>
        <label>Cognome Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Cliente__c</fullName>
        <formula>Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Cliente_input__c</fullName>
        <label>Email Cliente (input)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Ordine__c</fullName>
        <label>Id Ordine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Reso__c</fullName>
        <label>Id Reso</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Store__c</fullName>
        <label>Id Store</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lingua_di_Preferenza__c</fullName>
        <formula>text(Account.Lingua__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lingua di Preferenza</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lingua_di_Preferenza_input__c</fullName>
        <label>Lingua di Preferenza (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Casi</relationshipLabel>
        <relationshipName>Casi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nazione__c</fullName>
        <description>Nazione fatturazione del cliente</description>
        <formula>Account.PersonMailingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nazione</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione_input__c</fullName>
        <label>Nazione (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Cliente__c</fullName>
        <formula>Account.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nome Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Cliente_input__c</fullName>
        <label>Nome Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordine</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Ticket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reso</label>
        <referenceTo>Transaction_Detail__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Ticket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <formula>text(Account.Sesso__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sesso</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso_input__c</fullName>
        <label>Sesso (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <formula>Account.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Telefono</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_input__c</fullName>
        <label>Telefono (input)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Titolo_Cliente__c</fullName>
        <formula>text(Account.Salutation)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Titolo Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titolo_Cliente_input__c</fullName>
        <label>Titolo Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Dettaglio_Wishlist__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wishlists1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wishlist__c</fullName>
        <label>Wishlist</label>
        <referenceTo>Wishlist__c</referenceTo>
        <relationshipLabel>Dettagli Wishlist</relationshipLabel>
        <relationshipName>Dettagli_Wishlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Wishlist</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dettaglio Wishlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dettagli Wishlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <fields>
        <fullName>Citta__c</fullName>
        <label>Città</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione__c</fullName>
        <label>Nazione</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <label>Telefono</label>
        <type>Phone</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Task_ResoCambioStore__c</fullName>
        <label>Task_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Wishlist__c</fullName>
        <label>Task_Wishlist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/objects/Slave_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Slave Data</relationshipLabel>
        <relationshipName>Slave_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <label>Id Cliente DW</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <label>Slave Data</label>
    <nameField>
        <label>Slave Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slave Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <label>Id Cliente DW</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Wishlist__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wishlists</relationshipLabel>
        <relationshipName>Wishlists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wishlist</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Wishlist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wishlists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestTask.cls
@RestResource(urlMapping='/Task_v1.0/*')
global without sharing class RestTask  {


    @HttpPost
    global static ResponseWrapper doPost(Task attivita) {
        return new RestTaskHandler().doPostHandler(attivita);
    }

 /* 
    @HttpGet
    global static ResponseWrapper doGet() {
        return new RestCaseHandler().doGetHandler(RestContext.request, RestContext.response);
    }
  */  

 /* 
    @HttpPut
    global static ResponseWrapper doPatch(Case c) {
        return new RestCaseHandler().doPatchHandler(c);
    }
  */  

    public static SObject getMemberByExtIdAS400(String id){
        SObject a = (Account)GenericDao.getAllFieldsResultById('Account', 'Id_Cliente_DW__c', id);

        if(a == null){
            System.debug('Master not found. Searching for slave.');

            Sobject sd = GenericDao.getAllFieldsResultById('Slave_Data__c', 'Id_Cliente_DW__c', id);

            System.debug('Slave is ' + sd);

            return sd;
        }

        return a;
    }

    public static void copyTaskAccountField(Task c){
        c.Titolo_Cliente_Input__c = c.Titolo_Cliente__c;
        c.Nome_Cliente_Input__c = c.Nome_Cliente__c;
        c.Cognome_Cliente_Input__c = c.Cognome_Cliente__c;
        c.Sesso_Input__c = c.Sesso__c;
        c.Email_Cliente_Input__c = c.Email_Cliente__c;
        c.Telefono_Input__c = c.Telefono__c;
        c.Nazione_Input__c = c.Nazione__c;
        c.Citta_Input__c = c.Citta__c;
        c.Lingua_di_Preferenza_Input__c = c.Lingua_di_Preferenza__c;
    }

    public static Location__c getLocation(String id){
        return (Location__c)GenericDao.getAllFieldsResultById('Location__c', 'Id_Location_Micros__c', id);
    }

    public static Transaction__c getTransaction(String name){
        return (Transaction__c)GenericDao.getAllFieldsResultById('Transaction__c', 'Name', name);
    }


    public static Transaction_Detail__c getTransactionDetail(String name){
        return (Transaction_Detail__c)GenericDao.getAllFieldsResultById('Transaction_Detail__c', 'Name', name);
    }

    public static Task getTaskById(String id){
        return (Task)GenericDao.getAllFieldsResultById('Task', 'Id', id);
    }


    public class RestTaskHandler extends ProvaHandler{
        public Override Object get(RestRequest req,  RestResponse res){
            return null;
        }

        public Override SObject beforeUpdate(RestRequest req,  RestResponse res, SObject obj){
            return obj;
        }

        public Override ResponseWrapper afterUpdateResponse(RestRequest req,  RestResponse res, SObject obj){
            return null;
        }

        public Override Boolean beforeInsert(SObject obj){
            Task t = (Task)obj;

            System.debug('obj:' + obj);
            
            Sobject a = null;
            String idClient = null;
            String ownerId = null;
            String idStore = t.id_store__c;

            RecordTypeSetting__c cs = RecordTypeSetting__c.getValues('General');
            String rtResoCambioStore = cs.Task_ResoCambioStore__c;
            String rtWishlist = cs.Task_Wishlist__c;

            Map<String, String> rtMap = new Map<String, String>();
            rtMap.put('Wishlist', rtWishlist);
            rtMap.put('ResoCambioStore', rtResoCambioStore);

            String rtName = rtMap.get(t.Origine_Task__c);

            if(rtName == null){
                throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Origine_Task__c');
            }

            if(idStore == null){
                obj.put('Alert_Dati_Ecommerce__c', true);
                //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - id_store__c');
            } else {
                User u = GenericDao.getUserByCodiceBuotique(idStore);

                System.debug('u:' + u);

                if(u == null){
                    obj.put('Alert_Dati_Ecommerce__c', true);
                    //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_VALID + ' - id_store__c');
                } else {
                    ownerId = u.id;
                }

                Location__c l = RestCase.getLocation(idStore);
                System.debug('Location__c ' + l);

                if(l == null){
                    //SETALERT DATI ECOMMERCE YES
                    obj.put('Alert_Dati_Ecommerce__c', true);
                    //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - id_Store__c');
                } else {
                    obj.put('Location__c', l.id);
                }
            }         

            RestTask.copyTaskAccountField(t);

            if(t.Id_Cliente__c != null){
               a =  RestTask.getMemberByExtIdAS400(t.Id_Cliente__c);
            }  

            if(a == null){
                a = GenericDao.insertAccountForCaseTask(t);
                //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Id_Cliente__c');
            }

            if(a != null){
                String objectType = a.getSobjectType().getDescribe().getName();

                if(objectType == 'Account'){
                    idClient = a.id;
                } else if (objectType == 'Slave_Data__c'){
                    idClient = (String)a.get('Account__c');
                }
            } else {
                obj.put('Alert_Dati_Ecommerce__c', true);
            }

            if(t.id_ordine__c != null){
                Transaction__c tr = RestTask.getTransaction(t.id_ordine__c);

                if(tr == null){
                    //SETALERT DATI ECOMMERCE YES
                    obj.put('Alert_Dati_Ecommerce__c', true);
                    //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - id_ordine__c');
                } else {
                    obj.put('Ordine__c', tr.id);
                }
            }

            if(t.id_reso__c != null){
                Transaction_Detail__c tr = RestTask.getTransactionDetail(t.id_reso__c);

                if(tr == null){
                    //SETALERT DATI ECOMMERCE YES
                    obj.put('Alert_Dati_Ecommerce__c', true);
                    //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - id_reso__c');
                } else {
                    obj.put('Reso__c', tr.id);
                }
            }

            if(ownerId != null){
                obj.put('OwnerId', ownerId);
            } 

            obj.put('WhatId', idClient);
            obj.put('Account__c', idClient);
            obj.put('RecordTypeId', rtName);
            obj.put('ActivityDate', System.today());

            System.debug('obj ' + obj);

            return true;
        }

        public Override SObject afterInsert(SObject obj){
            Task t = (Task)obj;
            
            if(t.WhatId != null && t.Origine_Task__c == 'Wishlist'){
                //Crea wishlist e prodotti collegati
                String jsonProdotti = t.scheda_prodotto__c;
                Type listType = Type.forName('List<RestTask.ProductWrapper>');
                List<String> skuList = new List<String>();
                Map<String, Integer> skuQtyMap = new Map<String, Integer>();

                System.debug('jsonProdotti ' + jsonProdotti);

                List<ProductWrapper> prodotti = (List<ProductWrapper>)JSON.deserialize(jsonProdotti, listType);

                for(ProductWrapper pw : prodotti){
                    skuList.add(pw.prodotto);
                    skuQtyMap.put(pw.prodotto, pw.quantita);
                }

                System.debug('prodotti ' + prodotti);

                if(prodotti != null && !prodotti.isEmpty()){
                    List<Dettaglio_Wishlist__c> dettagli2Insert = new List<Dettaglio_Wishlist__c>();

                    WishList__c wl = new Wishlist__c(); 
                    wl.Cliente__c = t.WhatId;
                    wl.Data_inserimento__c = System.today();

                    insert wl;
                    
                    System.debug('Wishlist ' + wl);

                    t.Wishlist__c = wl.id;
                    update t;

                    for(Product__c prodotto : [select id, Item_ID__c from Product__c where Item_ID__c in :skuList]){
                        dettagli2Insert.add(new Dettaglio_Wishlist__c(
                            Prodotto__c = prodotto.id,
                            Wishlist__c = wl.id,
                            Quantita__c = skuQtyMap.get(prodotto.Item_ID__c)
                        ));
                    }

                    System.debug('dettagli2Insert ' + dettagli2Insert);

                    if(!dettagli2Insert.isEmpty()){
                        insert dettagli2Insert;
                    }
                }
            }

             obj = RestTask.getTaskById(obj.id);

            return obj;
        }

        public Override String getObjectName(){
            return 'attivita';
        }
    }


    public class ProductWrapper{
        public String prodotto{get;set;}
        public Integer quantita{get;set;}

        public ProductWrapper(String p, Integer q){
            prodotto = p;
            quantita = q;
        }
    }
}