src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Privacy_1__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Customer acceptance of the Privacy Statement</inlineHelpText>
        <label>Consenso marketing (old)</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codice_Cassa__c</fullName>
        <label>Codice Cassa</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Scontrino__c</fullName>
        <label>Data Scontrino</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Listino__c</fullName>
        <label>Prezzo di Listino (Sede)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_Listino__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Vendita__c</fullName>
        <label>Prezzo di Vendita (Sede)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_Vendita__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Quantita__c</fullName>
        <label>Quantità</label>
        <summarizedField>Transaction_Detail__c.Quantita__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Codice_Cassa__c</fullName>
        <label>Codice Cassa</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Scontrino__c</fullName>
        <label>Data Scontrino</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Listino__c</fullName>
        <description>Prezzo di listino espresso nella valuta del negozio comprensivo di VAT</description>
        <label>Prezzo di Listino (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Vendita__c</fullName>
        <description>Prezzo effettivo pagato dal cliente lordo iva netto tasse- Ricavabile come full price - discount value</description>
        <label>Prezzo di Vendita (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantita__c</fullName>
        <description>Numerico positivo o negativo (reso)</description>
        <label>Quantità</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/onTransactionDetailTriggerHandlerTest.cls
@isTest
private class onTransactionDetailTriggerHandlerTest {
    
    static testMethod void CreateGiftActivityTest() {     
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            Account a1 	= new Account();
            a1.LastName = 'TestLastName1';
            a1.Privacy_1__c = true;
            insert a1;
            
            Product__c p 	= new Product__c();
            p.Name		= 'ProductTest';
            insert p;
            
            Transaction__c t 	= new Transaction__c();
            t.Account__c		= a1.Id;
            insert t;
            
            Transaction_Detail__c td 	= new Transaction_Detail__c();
            td.Transaction__c			= t.Id;
            td.Product__c				= p.Id;
            td.Gift__c					= true;
            td.Quantita__c = 1.0;
            td.CurrencyIsoCode = 'EUR';
            td.Codice_Cassa__c ='1';
            td.Prezzo_di_Listino__c = 300.00;
            td.Prezzo_di_Vendita__c = 150.00;
            td.Data_Scontrino__c = system.today();
            
            insert td;
            
            delete td;
            
        }
        Test.stopTest();
        
        
    }
    static testMethod void CreatebulkifiedTestTD() {     
        /*
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            Account a1 	= new Account();
            a1.LastName = 'TestLastName1';
            a1.Privacy_1__c = true;
            insert a1;
            
            Product__c p 	= new Product__c();
            p.Name		= 'ProductTest';
            insert p;
            
            Transaction__c t 	= new Transaction__c();
            t.Account__c		= a1.Id;
            insert t;
            
            Transaction_Detail__c td 	= new Transaction_Detail__c();
            td.Transaction__c			= t.Id;
            td.Product__c				= p.Id;
            td.Gift__c					= true;
            td.Quantita__c = 1.0;
            td.CurrencyIsoCode = 'EUR';
            td.Codice_Cassa__c ='1';
            td.Prezzo_di_Listino__c = 300.00;
            td.Prezzo_di_Vendita__c = 150.00;
            
            insert td;
            
            delete td;
           
        }
        Test.stopTest();
         */
        
    }
}