src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente E-commerce</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>Id cliente AS400</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>It’s the boutique the client seems to prefer for her/his purchases, over the years. We consider both the total amount spent and recency of purchase: recent purchase weight more than past ones (-10% weight going back year after year)</inlineHelpText>
        <label>Boutique di assegnazione</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Alert_Dati_Ecommerce__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alert Dati E-commerce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citta__c</fullName>
        <formula>Account.PersonMailingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Città</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citta_input__c</fullName>
        <label>Città (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cognome_Cliente__c</fullName>
        <formula>Account.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cognome Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cognome_Cliente_input__c</fullName>
        <label>Cognome Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Cliente__c</fullName>
        <formula>Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Cliente_input__c</fullName>
        <label>Email Cliente (input)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Ordine__c</fullName>
        <label>Id Ordine</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Store__c</fullName>
        <label>Id Store</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lingua_di_Preferenza__c</fullName>
        <formula>text(Account.Lingua__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lingua di Preferenza</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lingua_di_Preferenza_input__c</fullName>
        <label>Lingua di Preferenza (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Casi</relationshipLabel>
        <relationshipName>Casi</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Motivazione_Reso_Cambio__c</fullName>
        <label>Motivazione Reso Cambio</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione__c</fullName>
        <description>Nazione fatturazione del cliente</description>
        <formula>Account.PersonMailingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nazione</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione_input__c</fullName>
        <label>Nazione (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Cliente__c</fullName>
        <formula>Account.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nome Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nome_Cliente_input__c</fullName>
        <label>Nome Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordine</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Ticket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origine_Ticket__c</fullName>
        <label>Origine Ticket</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prodotto_Selezionato__c</fullName>
        <label>Prodotto Selezionato</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prodotto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prodotto</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Ticket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <formula>text(Account.Sesso__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sesso</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso_input__c</fullName>
        <label>Sesso (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taglia_non_presente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Taglia non presente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <formula>Account.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Telefono</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_input__c</fullName>
        <label>Telefono (input)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tipologia__c</fullName>
        <label>Tipologia</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titolo_Cliente__c</fullName>
        <formula>text(Account.Salutation)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Titolo Cliente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titolo_Cliente_input__c</fullName>
        <label>Titolo Cliente (input)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <fields>
        <fullName>Citta__c</fullName>
        <label>Città</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nazione__c</fullName>
        <label>Nazione</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <label>Telefono</label>
        <type>Phone</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <fields>
        <fullName>Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Caso_BrandSpecialist__c</fullName>
        <label>Caso_BrandSpecialist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_CustomerCare__c</fullName>
        <label>Caso_CustomerCare</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_OMS__c</fullName>
        <label>Caso_OMS</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambioStore__c</fullName>
        <label>Caso_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambio__c</fullName>
        <label>Caso_ResoCambio</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/objects/Slave_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Slave Data</relationshipLabel>
        <relationshipName>Slave_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <label>Id Cliente DW</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sesso__c</fullName>
        <label>Sesso</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefono</label>
        <type>Checkbox</type>
    </fields>
    <label>Slave Data</label>
    <nameField>
        <label>Slave Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slave Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id_Cliente_DW__c</fullName>
        <label>Id Cliente DW</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Cliente__c</fullName>
        <label>Id Cliente</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Id_Location_Micros__c</fullName>
        <label>Id Location Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestCase.cls
@RestResource(urlMapping='/Ticket_v1.0/*')
global without sharing class RestCase  {
    
    
    @HttpPost
    global static ResponseWrapper doPost(Case ticket) {
        return new RestCaseHandler().doPostHandler(ticket);
    }
    
    //Akshay decomentato 17/10/2018
    @HttpGet
    global static ResponseWrapper doGet() {
        return new RestCaseHandler().doGetHandler(RestContext.request, RestContext.response);
    }
    //Akshay decomentato  17/10/2018
    @HttpPut
    global static ResponseWrapper doPatch(Case ticket) {
        return new RestCaseHandler().doPatchHandler(ticket);
    }
    
    public static Case getCaseById(String id){
        return (Case)GenericDao.getAllFieldsResultById('Case', 'Id', id);
    }
    
    public static Location__c getLocation(String id){
        return (Location__c)GenericDao.getAllFieldsResultById('Location__c', 'Id_Location_Micros__c', id);
    }
    
    public static Transaction__c getTransaction(String name){
        return (Transaction__c)GenericDao.getAllFieldsResultById('Transaction__c', 'Name', name);
    }
    
    
    public static Transaction_Detail__c getTransactionDetail(String name){
        return (Transaction_Detail__c)GenericDao.getAllFieldsResultById('Transaction_Detail__c', 'Name', name);
    }
    
    
    public static SObject getMemberByExtId(String id){
        SObject a = (Account)GenericDao.getAllFieldsResultById('Account', 'Id_Cliente_DW__c', id);
        
        if(a == null){
            System.debug('Master not found. Searching for slave.');
            
            Sobject sd = GenericDao.getAllFieldsResultById('Slave_Data__c', 'Id_Cliente_DW__c', id);
            
            System.debug('Slave is ' + sd);
            
            return sd;
        }
        
        return a;
    }
    
    public static void copyCaseAccountField(Case c){
        c.Titolo_Cliente_Input__c = c.Titolo_Cliente__c;
        c.Nome_Cliente_Input__c = c.Nome_Cliente__c;
        c.Cognome_Cliente_Input__c = c.Cognome_Cliente__c;
        c.Sesso_Input__c = c.Sesso__c;
        c.Email_Cliente_Input__c = c.Email_Cliente__c;
        c.Telefono_Input__c = c.Telefono__c;
        c.Nazione_Input__c = c.Nazione__c;
        c.Citta_Input__c = c.Citta__c;
        c.Lingua_di_Preferenza_Input__c = c.Lingua_di_Preferenza__c;
    }
    
    public class RestCaseHandler extends ProvaHandler{
        public Override Object get(RestRequest req,  RestResponse res){
            
            String reqUri = req.requestURI.substring(1);
            system.Debug('reqUri : ' + reqUri);
            String[] arr = reqUri.split('\\/');
            system.Debug('arr : ' + arr);
            Integer arrSize = arr.size();
            String service = arr[0];
            String parameter = arrSize > 1 ? arr[1] : null;
            String relatedResource = arrSize > 2 ? arr[2] : null;
            String idRelatedResource = arrSize > 3 ? arr[3] : null;
            List<sObject> objList;
            sObject obj;
            Set<String> skuIDValue = new Set<String>();
            
            //Akshay 1/16/2019 -- FIX [notifyme] Errore GET ticket creato (Modified containsAny with contains)
            if(parameter.contains('sku=')){
                String[] skuValue;
                String value = parameter.remove('sku=');
                system.debug('value : ' + value);
                
                skuValue = value.split(',');
                
                for(String str : skuValue){
                    skuIDValue.add(str);
                }
                system.debug('skuValue : ' + skuValue);
                if(value != null && value != '' &&  skuIDValue.size() > 0){
                    objList =  GenericDao.getAllFieldsResultByCondition('Case' , 'SKU__c', skuIDValue);
                }else{
                    throw new ResourceException(Label.ERR_0002,  ' SKU è obbligatorio');
                }
                
            }else{
                obj =  GenericDao.getAllFieldsResultById('Case' , 'Id', parameter);
            }
            
            Object result;
            if(obj != null){
                result = obj;
            }
            if(objList != null){
                result = objList;
            }
            
            return result;
        }
        
        public Override SObject beforeUpdate(RestRequest req,  RestResponse res, SObject obj){
            String reqUri = req.requestURI.substring(1);
            
            String[] arr = reqUri.split('\\/');
            Integer arrSize = arr.size();
            String service = arr[0];
            String id = arrSize > 1 ? arr[1] : null;
            String relatedResource = arrSize > 2 ? arr[2] : null;
            String idRelatedResource = arrSize > 3 ? arr[3] : null;
            
            List<Case> result = [SELECT Id FROM Case Where Id =:id];
            if(result != null && !result.isEmpty()){
                Case m = result.get(0); 
                obj.id = m.id;
            } else {
                throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Id');
            }
            
            
            return obj;
        }
        
        public Override ResponseWrapper afterUpdateResponse(RestRequest req,  RestResponse res, SObject obj){
            ResponseWrapper result = createSuccessResult(afterInsert(obj));
            return result;
        }
        
        public Override Boolean beforeInsert(SObject obj){
            Case c = (Case)obj;
            
            System.debug('CASE: ' + c);
            
            Sobject a = null;
            String idClient = null;
            RecordTypeSetting__c cs = RecordTypeSetting__c.getValues('General');
            String rtResoCambio = cs.Caso_ResoCambio__c;
            String rtResoCambioStore = cs.Caso_ResoCambioStore__c;
            String rtCustomerCare = cs.Caso_CustomerCare__c;
            String rtBrandSpecialist = cs.Caso_BrandSpecialist__c;
            String rtNotifyMe = cs.Caso_NotifyMe__c;  //Akshay Aggiunto NotifyMe 17/10/2018
            String rtOMS = cs.Caso_OMS__c;
            
            Map<String, String> rtMap = new Map<String, String>();
            rtMap.put('ResoCambio', rtResoCambio);
            rtMap.put('ResoCambioStore', rtResoCambioStore);
            rtMap.put('CustomerCare', rtCustomerCare);
            rtMap.put('BrandSpecialist', rtBrandSpecialist);
            rtMap.put('NotifyMe', rtNotifyMe);
            rtMap.put('OMS', rtOMS);
            
            String rtName = rtMap.get(c.Origine_Ticket__c);
            
            if(rtName == null){
                throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Origine_Ticket__c');
            }
            
            RestCase.copyCaseAccountField(c);
            
            if(c.Id_Cliente__c != null && c.Id_Cliente__c != ''){
                a =  RestCase.getMemberByExtId(c.Id_Cliente__c);
            } 
            
            // TEN GROUP: Add condition for create account when Origine_Ticket__c is CustomerCare 
            //            and Taglia_non_presente__c false, for others Origine_Ticket__c create always the account
            if(a == null){
                if(c.Origine_Ticket__c == 'CustomerCare'){
                    if(!c.Taglia_non_presente__c){
                        a = GenericDao.insertAccountForCaseTask(c);
                    }
                } else {
                    a = GenericDao.insertAccountForCaseTask(c);
                    //throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Id_Cliente__c');
                }
            }
            
            if(a != null){
                system.debug('QUA' );
                String objectType = a.getSobjectType().getDescribe().getName();
                
                // Gestione CLient ID
                if(objectType == 'Account'){
                    idClient = a.id;
                } else if (objectType == 'Slave_Data__c'){
                    idClient = (String)a.get('Account__c');
                }
            } else {
                obj.put('Alert_Dati_Ecommerce__c', true);
            }
            
            // Gestione Subject
            if(c.Origine_Ticket__c == 'ResoCambio' || 
               c.Origine_Ticket__c == 'ResoCambioStore'
              ){
                  obj.put('Subject', ((c.Tipologia__c == 'E' ? 'Cambio - ' : 'Reso - ') + c.Motivazione_Reso_Cambio__c));
              }
            
            // Gestione LookUp Prodotto
            if(c.Origine_Ticket__c == 'BrandSpecialist'){
                obj.put('Subject', 'Brand Specialist Request');
                
                if(!String.isEmpty(c.Prodotto_Selezionato__c)){
                    List<Product__c> prodotti = [select id from Product__c where Item_ID__c = :c.Prodotto_Selezionato__c];
                    
                    if(prodotti != null && !prodotti.isEmpty()){
                        obj.put('Prodotto__c', prodotti.get(0).id);
                    } else {
                        //SETALERT DATI ECOMMERCE YES
                        obj.put('Alert_Dati_Ecommerce__c', true);
                    }
                }
            }
            
            // Gestione NotifyMe
            if(c.Origine_Ticket__c == 'NotifyMe'){}
            
            // Gestione LookUp Store
            if(c.id_Store__c != null){
                Location__c l = RestCase.getLocation(c.id_Store__c);
                System.debug('Location__c ' + l);
                
                if(l == null){
                    if(c.Origine_Ticket__c == 'ResoCambioStore'){
                        //SETALERT DATI ECOMMERCE YES
                        obj.put('Alert_Dati_Ecommerce__c', true);
                    }
                } else {
                    obj.put('Location__c', l.id);
                }
            }
            
            // Gestione LookUp Ordine
            if(c.id_ordine__c != null){
                Transaction__c tr = RestCase.getTransaction(c.id_ordine__c);
                
                if(tr == null){
                    if( c.Origine_Ticket__c == 'ResoCambio' || c.Origine_Ticket__c == 'ResoCambioStore' ||
                       c.Origine_Ticket__c == 'OMS'){
                           //SETALERT DATI ECOMMERCE YES
                           obj.put('Alert_Dati_Ecommerce__c', true);
                       }
                } else {
                    obj.put('Ordine__c', tr.id);
                }
            }
            
            // Gestione LookUp Reso
            if(c.id_reso__c != null){
                Transaction_Detail__c tr = RestCase.getTransactionDetail(c.id_reso__c);
                
                if(tr == null){
                    if(!String.isBlank(c.id_reso__c) && (c.Origine_Ticket__c == 'ResoCambio' || c.Origine_Ticket__c == 'ResoCambioStore' ||
                                                         c.Origine_Ticket__c == 'OMS')){
                                                             //SETALERT DATI ECOMMERCE
                                                             obj.put('Alert_Dati_Ecommerce__c', true);
                                                         }
                } else {
                    obj.put('Reso__c', tr.id);
                }
            }
            
            obj.put('AccountId', idClient);
            obj.put('RecordTypeId', rtName);
            
            System.debug('obj ' + obj);
            
            return true;
        }
        
        public Override SObject afterInsert(SObject obj){
            obj = RestCase.getCaseById(obj.id);
            
            return obj;
        }
        
        public Override String getObjectName(){
            return 'ticket';
        }
    }
    
    
    
}