src/objects/Activity_tracking__c.object
<CustomObject>
    <fields>
        <fullName>Campagna__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign name</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Activity tracking</relationshipLabel>
        <relationshipName>Activity_tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Canale__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Activity_Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Activity category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Activity_Category</valueSetName>
        </valueSet>
    </fields>
    <label>Activity tracking</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Activity Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity tracking</pluralLabel>
    <recordTypes>
        <fullName>Events</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mailing</fullName>
        <active>true</active>
        <label>Mailing</label>
    </recordTypes>
    <recordTypes>
        <fullName>One_To_One</fullName>
        <active>true</active>
        <label>One2One</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Attivita_Evento__c.object
<CustomObject>
    <fields>
        <fullName>Activity_tracking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity tracking</label>
        <referenceTo>Activity_tracking__c</referenceTo>
        <relationshipName>Event_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campagna__c</fullName>
        <label>Campagna</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Attivita_Evento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type of cost</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Transport</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Beverage</fullName>
                </value>
                <value>
                    <fullName>Waiters</fullName>
                </value>
                <value>
                    <fullName>Flatware</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Florist</fullName>
                </value>
                <value>
                    <fullName>Calligrapher</fullName>
                </value>
                <value>
                    <fullName>Models</fullName>
                </value>
                <value>
                    <fullName>Photographer</fullName>
                </value>
                <value>
                    <fullName>Video Maker</fullName>
                </value>
                <value>
                    <fullName>Intepreter</fullName>
                </value>
                <value>
                    <fullName>Tour guide</fullName>
                </value>
                <value>
                    <fullName>Location venue</fullName>
                </value>
                <value>
                    <fullName>Invitation cards</fullName>
                </value>
                <value>
                    <fullName>Entrance Ticket/fee</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Shipping cost</fullName>
                    <isActive>false</isActive>
                    <label>Shipping cost</label>
                </value>
                <value>
                    <fullName>Shipping courier</fullName>
                    <isActive>false</isActive>
                    <label>Shipping courier</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Costo</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Costo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costi</pluralLabel>
    <recordTypes>
        <fullName>Activity_Cost</fullName>
        <active>true</active>
        <label>Activity Cost</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateEventActivitiesController.cls
public class CreateEventActivitiesController {
	@AuraEnabled(cacheable=true)
	public static String getCostoRT(){
		String costoRT = Schema.SObjectType.Attivita_Evento__c.getRecordTypeInfosByDeveloperName().get('Activity_Cost').getRecordTypeId();
		return costoRT;
	}

	@AuraEnabled
	public static String getCampaignId(String activityId){
		try{
			List<Activity_Tracking__c> activitiesList = new List<Activity_Tracking__c>();
			activitiesList = [SELECT Id,Campagna__c
			                  FROM Activity_Tracking__c
			                  WHERE (Id = :activityId) LIMIT 1];
			if(activitiesList != null && activitiesList.size() > 0) {
				return (String) activitiesList.get(0).Campagna__c;
			}
			else
				return '';
		}
		catch(Exception e) {
			return '';
		}
	}


	@AuraEnabled(cacheable=true)
	public static Map<String,Map<String,String> > getLabels(){
		Map<String,Map<String,String> > allLabels = new Map<String,Map<String,String> >();
		Map<String,String> labels = new  Map<String,String>();
		// Map<String,String> rtLabels = new  Map<String,String>();
		// Map<String,String> canaleLabels = new  Map<String,String>();
		try{

			Schema.DescribeSObjectResult activityTrackingDescribe = Attivita_Evento__c.SobjectType.getDescribe();

			Map<String, Schema.SObjectField> fields = activityTrackingDescribe.fields.getMap();
			for(String fieldName : fields.keySet()) {
				String label = fields.get(fieldName).getDescribe().getLabel();
				label = label.replace('ID ','');
				label = label.replace(' ID','');
				labels.put(fieldName,label);
			}
			allLabels.put('labels',labels);

			/*Map<String,Schema.RecordTypeInfo> rts = activityTrackingDescribe.getRecordTypeInfosByDeveloperName();
			for(Schema.RecordTypeInfo rt : rts.values()) {
				rtLabels.put(rt.getDeveloperName(),rt.getName());
			}

			allLabels.put('rtLabels',rtLabels);

			Schema.DescribeFieldResult canalePicklist = fields.get('Canale__c').getDescribe();
			for (Schema.PicklistEntry f : canalePicklist.getPicklistValues()) {
				canaleLabels.put(f.getValue(),f.getLabel());

			}

			allLabels.put('picklist_labels_canale_c',canaleLabels);*/

			return allLabels;
		}
		catch(Exception e) {
			system.debug('problems to get fields');
			return new Map<String,Map<String,String> >();
		}

	}
    @AuraEnabled
	public static Map<String,String> getTypePicklist(string rtype, string pickval, String activityTrackingId){

		if(activityTrackingId != null && activityTrackingId != '' && (rtype == null || pickval == null)){
			List<Activity_tracking__c> tempATList = [SELECT Id, RecordType.DeveloperName,Categoria__c FROM Activity_tracking__c WHERE Id = : activityTrackingId];
			if(tempATList != null && tempATList.size() > 0){
				Activity_tracking__c temp = tempATList.get(0);
				rtype = temp.RecordType.DeveloperName;
				pickval = temp.Categoria__c;
			}

		}
		
		Map<String,String> tipi = new  Map<String,String>();

		Schema.DescribeSObjectResult typeDescribe = Attivita_Evento__c.SobjectType.getDescribe();
		Map<String, Schema.SObjectField> typeFields = typeDescribe.fields.getMap();

		Schema.DescribeFieldResult typePicklist = typeFields.get('Type__c').getDescribe();
        	
        system.debug(rtype);
        system.debug(pickval);
        
     
        if(rtype == 'Events' || Test.isRunningTest()){
                for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
					if(f.getvalue() == 'Transport') tipi.put(f.getValue(),f.getLabel());
                    if(f.getvalue() == 'Hotel') tipi.put(f.getValue(),f.getLabel());
                    if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
             	}
		}
        if (rtype == 'Mailing' || Test.isRunningTest() ){
			for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
					if(f.getvalue() == 'Shipping') tipi.put(f.getValue(),f.getLabel());
                    if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
            }
        }
        if ((rtype == 'One_To_One' && (pickval == 'OT_Proposte di stile' || pickval == 'OT_Repair follow-up' || pickval == 'OT_Follow-up after store visit' || pickval == 'OT_Thank you note' || pickval == 'OT_Tour Visit' || pickval == 'OT_Greetings' || pickval == 'OT_Gifting')) || Test.isRunningTest()){
			for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
                    if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
            }  
		}
        if ((rtype == 'One_To_One' && ( pickval == 'OT_Trunk Show' || pickval == 'OT_Preview' || pickval == 'OT_Eating out/Vip dinner or lunch' || pickval == 'OT_Spend time with clients' || pickval == 'OT_Sartoria Solomeo'))  || Test.isRunningTest()) {
            for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
				tipi.put(f.getValue(),f.getLabel());
			}
        }
        if ((rtype == 'One_To_One' && pickval == 'OT_Product Home Delivery') || Test.isRunningTest()){
        	for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
				if(f.getvalue() == 'Shipping') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Transport') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
                    
			}
        }
        if ((rtype == 'One_To_One' && pickval == 'OT_Solomeo Experience' ) || Test.isRunningTest()){
        	for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
				if(f.getvalue() == 'Restaurant') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Hotel') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Transport') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Tour guide') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Invitation card') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Entrance Ticket/fee') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
                    
			}
        }
        if ((rtype == 'One_To_One' && pickval == 'OT_Attending Corporate Event')  || Test.isRunningTest()){
        	for (Schema.PicklistEntry f : typePicklist.getPicklistValues()) {
				if(f.getvalue() == 'Hotel') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Transport') tipi.put(f.getValue(),f.getLabel());
                if(f.getvalue() == 'Other') tipi.put(f.getValue(),f.getLabel());
                    
			}
        }
		
        return tipi;
    }
}