src/objects/Admin_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email_Notifica_Batch__c</fullName>
        <label>Email Notifica Batch</label>
        <type>Email</type>
    </fields>
    <label>Admin Setting</label>
</CustomObject>

src/objects/Relazione_Ghost__c.object
<CustomObject>
    <description>Oggetto di sistema creato per gestire trigger di creazione relazione</description>
    <fields>
        <fullName>Legame_Cliente__c</fullName>
        <label>Legame Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legame_Cliente_in_Relazione__c</fullName>
        <label>Legame Cliente in Relazione</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Legame_Cliente__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Relazione Ghost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduledBatchDeleteRelazioneGhostTest.cls
@isTest
private class ScheduledBatchDeleteRelazioneGhostTest {

    static testMethod void DeleteRelazioniTest() {

	/*        
  	Test for: 
    - ScheduledBatchDeleteRelazioneGhost
    - BatchDeleteRelazioneGhost
  	*/        
        
        Relazione_Ghost__c r   				= new Relazione_Ghost__c();
        r.Legame_Cliente__c					= 'Marito';
        r.Legame_Cliente_in_Relazione__c	= 'Moglie';
        insert r;
        
        Admin_Setting__c e 			= new Admin_Setting__c();
        e.Email_Notifica_Batch__c 	= 'test@test.test';
		insert e;
        
		Test.startTest();

        ScheduledBatchDeleteRelazioneGhost sbac = new ScheduledBatchDeleteRelazioneGhost();        
    	SchedulableContext sc;
    	sbac.execute(sc);
    
        Test.stopTest();
               
    }
    
}