src/objects/Associated__c.object
<CustomObject>
    <description>Anagrafiche venditori negozi (collegato a Store di riferimento)</description>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Data_Scontrino__c</fullName>
        <label>Data Scontrino</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Importo_Sconto_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Sconto_EUR__c, 
&quot;CAD&quot;, Sconto_CAD__c, 
&quot;CHF&quot;, Sconto_CHF__c, 
&quot;CNY&quot;, Sconto_CNY__c, 
&quot;EUR&quot;, Sconto_EUR__c, 
&quot;GBP&quot;, Sconto_GBP__c, 
&quot;HKD&quot;, Sconto_HKD__c, 
&quot;JPY&quot;, Sconto_JPY__c, 
&quot;USD&quot;, Sconto_USD__c, 
&quot;MOP&quot;, Sconto_MOP__c, 
&quot;RUB&quot;, Sconto_RUB__c, 
&quot;AUD&quot;, Sconto_AUD__c, 
&quot;DKK&quot;, Sconto_DKK__c, 
Importo_Sconto__c)</formula>
        <label>Importo Sconto (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Listino_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Prezzo_di_listino_BRL__c, 
&quot;CAD&quot;, Prezzo_di_listino_CAD__c, 
&quot;CHF&quot;, Prezzo_di_listino_CHF__c, 
&quot;CNY&quot;, Prezzo_di_listino_CNY__c, 
&quot;EUR&quot;, Prezzo_di_listino_EUR__c, 
&quot;GBP&quot;, Prezzo_di_listino_GBP__c, 
&quot;HKD&quot;, Prezzo_di_listino_HKD__c, 
&quot;JPY&quot;, Prezzo_di_listino_JPY__c, 
&quot;USD&quot;, Prezzo_di_listino_USD__c,
&quot;MOP&quot;, Prezzo_di_listino_MOP__c,
&quot;AUD&quot;, Prezzo_di_listino_AUD__c,
&quot;DKK&quot;, Prezzo_di_listino_DKK__c,
&quot;RUB&quot;, Prezzo_di_listino_RUB__c,
&quot;KRW&quot;, Prezzo_di_listino_KRW__c,
&quot;AED&quot;, Prezzo_di_listino_AED__c,
&quot;PLN&quot;, Prezzo_di_listino_PLN__c,
&quot;QAR&quot;, Prezzo_di_listino_QAR__c,
&quot;SGD&quot;, Prezzo_di_listino_SGD__c,
&quot;SAR&quot;, Prezzo_di_listino_SAR__c,
Prezzo_di_Listino__c)</formula>
        <label>Retail price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Vendita_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Prezzo_di_vendita_BRL__c, 
&quot;CAD&quot;, Prezzo_di_vendita_CAD__c, 
&quot;CHF&quot;, Prezzo_di_vendita_CHF__c, 
&quot;CNY&quot;, Prezzo_di_vendita_CNY__c, 
&quot;EUR&quot;, Prezzo_di_vendita_EUR__c, 
&quot;GBP&quot;, Prezzo_di_vendita_GBP__c, 
&quot;HKD&quot;, Prezzo_di_vendita_HKD__c, 
&quot;JPY&quot;, Prezzo_di_vendita_JPY__c, 
&quot;USD&quot;, Prezzo_di_vendita_USD__c, 
&quot;MOP&quot;, Prezzo_di_vendita_MOP__c,
&quot;AUD&quot;, Prezzo_di_vendita_AUD__c,
&quot;DKK&quot;, Prezzo_di_vendita_DKK__c,
&quot;RUB&quot;, Prezzo_di_vendita_RUB__c,
&quot;KRW&quot;, Prezzo_di_vendita_KRW__c,
&quot;AED&quot;, Prezzo_di_vendita_AED__c,
&quot;PLN&quot;, Prezzo_di_vendita_PLN__c,
&quot;QAR&quot;, Prezzo_di_vendita_QAR__c,
&quot;SGD&quot;, Prezzo_di_vendita_SGD__c,
&quot;SAR&quot;, Prezzo_di_vendita_SAR__c,
Prezzo_di_Vendita__c)</formula>
        <label>Prezzo di Vendita (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, PSconto_BRL__c, 
&quot;CAD&quot;, PSconto_CAD__c, 
&quot;CHF&quot;, PSconto_CHF__c, 
&quot;CNY&quot;, PSconto_CNY__c, 
&quot;EUR&quot;, PSconto_EUR__c, 
&quot;GBP&quot;, PSconto_GBP__c, 
&quot;HKD&quot;, PSconto_HKD__c, 
&quot;JPY&quot;, PSconto_JPY__c, 
&quot;USD&quot;, PSconto_USD__c, 
&quot;MOP&quot;, PSconto_MOP__c,
&quot;DKK&quot;, PSconto_DKK__c,
&quot;AUD&quot;, PSconto_AUD__c,
&quot;RUB&quot;, PSconto_RUB__c,
&quot;KRW&quot;, PSconto_KRW__c,
&quot;PLN&quot;, PSconto_PLN__c,
&quot;QAR&quot;, PSconto_QAR__c,
&quot;SGD&quot;, PSconto_SGD__c,
&quot;SAR&quot;, PSconto_SAR__c,
 
PSconto__c)</formula>
        <label>% Sconto (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tipo_Vendita__c</fullName>
        <description>Flag che indica se è una vendita o un reso (valorizzato con s= sale, r= return, e= exchange) alimentato sia da Micros sia da Ecommerce</description>
        <label>Tipo Vendita</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <formula>CASESAFEID(Transaction__r.Account__c)</formula>
        <label>AccountId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Scontrino_KPI__c</fullName>
        <label>Data Scontrino KPI</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Scontrino__c</fullName>
        <label>Data Scontrino</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Importo_sconto_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Sconto_BRL__c, 
&quot;CAD&quot;, Sconto_CAD__c, 
&quot;CHF&quot;, Sconto_CHF__c, 
&quot;CNY&quot;, Sconto_CNY__c, 
&quot;EUR&quot;, Sconto_EUR__c, 
&quot;GBP&quot;, Sconto_GBP__c, 
&quot;HKD&quot;, Sconto_HKD__c, 
&quot;JPY&quot;, Sconto_JPY__c,
&quot;USD&quot;, Sconto_USD__c,
&quot;MOP&quot;, Sconto_MOP__c,
&quot;AUD&quot;, Sconto_AUD__c,
&quot;DKK&quot;, Sconto_DKK__c,
&quot;RUB&quot;, Sconto_RUB__c,
Importo_Sconto__c)</formula>
        <label>Importo Sconto (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nome_Location__c</fullName>
        <formula>Transaction__r.Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nome Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Scontrino__c</fullName>
        <label>Numero Scontrino</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_listino_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Prezzo_di_listino_BRL__c, 
&quot;CAD&quot;, Prezzo_di_listino_CAD__c,
&quot;CHF&quot;, Prezzo_di_listino_CHF__c,
&quot;CNY&quot;, Prezzo_di_listino_CNY__c,
&quot;EUR&quot;, Prezzo_di_Listino_EUR__c,
&quot;GBP&quot;, Prezzo_di_listino_GBP__c,
&quot;HKD&quot;, Prezzo_di_listino_HKD__c,
&quot;JPY&quot;, Prezzo_di_listino_JPY__c,
&quot;USD&quot;, Prezzo_di_listino_USD__c,
&quot;MOP&quot;, Prezzo_di_listino_MOP__c,
&quot;AUD&quot;, Prezzo_di_listino_AUD__c,
&quot;DKK&quot;, Prezzo_di_listino_DKK__c,
&quot;RUB&quot;, Prezzo_di_listino_RUB__c,
&quot;KRW&quot;, Prezzo_di_listino_KRW__c, 
&quot;AED&quot;, Prezzo_di_listino_AED__c, 
&quot;PLN&quot;, Prezzo_di_listino_PLN__c, 
&quot;QAR&quot;, Prezzo_di_listino_QAR__c, 
&quot;SGD&quot;, Prezzo_di_listino_SGD__c, 
&quot;SAR&quot;, Prezzo_di_listino_SAR__c, 
Prezzo_di_Listino__c)</formula>
        <label>Retail price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_vendita_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, Prezzo_di_vendita_BRL__c, 
&quot;CAD&quot;, Prezzo_di_vendita_CAD__c, 
&quot;CHF&quot;, Prezzo_di_vendita_CHF__c, 
&quot;CNY&quot;, Prezzo_di_vendita_CNY__c, 
&quot;EUR&quot;, Prezzo_di_Vendita_EUR__c, 
&quot;GBP&quot;, Prezzo_di_vendita_GBP__c, 
&quot;HKD&quot;, Prezzo_di_vendita_HKD__c, 
&quot;JPY&quot;, Prezzo_di_vendita_JPY__c, 
&quot;USD&quot;, Prezzo_di_vendita_USD__c, 
&quot;MOP&quot;, Prezzo_di_vendita_MOP__c,
&quot;AUD&quot;, Prezzo_di_vendita_AUD__c,
&quot;DKK&quot;, Prezzo_di_Vendita_DKK__c,
&quot;RUB&quot;, Prezzo_di_vendita_RUB__c,
&quot;KRW&quot;, Prezzo_di_vendita_KRW__c, 
&quot;AED&quot;, Prezzo_di_vendita_AED__c, 
&quot;PLN&quot;, Prezzo_di_vendita_PLN__c, 
&quot;QAR&quot;, Prezzo_di_vendita_QAR__c, 
&quot;SGD&quot;, Prezzo_di_vendita_SGD__c, 
&quot;SAR&quot;, Prezzo_di_vendita_SAR__c, 
Prezzo_di_Vendita__c)</formula>
        <label>Prezzo di Vendita (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Image_Reference__c</fullName>
        <label>Product Image Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SKU__c</fullName>
        <label>SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sconto_formula__c</fullName>
        <formula>CASE($User.CurrencyISOcode__c, 
&quot;BRL&quot;, PSconto_BRL__c, 
&quot;CAD&quot;, Pdi_Sconto_CAD__c, 
&quot;CHF&quot;, PSconto_CHF__c, 
&quot;CNY&quot;, PSconto_CNY__c, 
&quot;EUR&quot;, PSconto_EUR__c, 
&quot;GBP&quot;, PSconto_GBP__c, 
&quot;HKD&quot;, PSconto_HKD__c, 
&quot;JPY&quot;, PSconto_JPY__c, 
&quot;USD&quot;, PSconto_USD__c, 
&quot;MOP&quot;, PSconto_MOP__c,
&quot;AUD&quot;, PSconto_AUD__c,
&quot;DKK&quot;, PSconto_DKK__c,
&quot;RUB&quot;, PSconto_RUB__c,
&quot;KRW&quot;, PSconto_KRW__c,
&quot;AED&quot;, PSconto_AED__c,
&quot;PLN&quot;, PSconto_PLN__c,
&quot;QAR&quot;, PSconto_QAR__c,
&quot;SGD&quot;, PSconto_SGD__c,
&quot;SAR&quot;, PSconto_SAR__c,
PSconto__c)</formula>
        <label>% Sconto (formula)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated al quale è stata associata la vendita</description>
        <label>Seller</label>
        <referenceTo>Associated__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Dettagli_Transazione</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tipo_Vendita__c</fullName>
        <label>Tipo Vendita</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>R</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionDetialListViewController.cls
public with sharing class TransactionDetialListViewController {
	@AuraEnabled
	public static List<Transaction_Detail__c> getTransactionDetailsLimit5(String accId){


		List<Transaction_Detail__c> tDetails =  [SELECT Id,
		                                         Name,
		                                         Importo_sconto_formula__c,
		                                         Sconto_formula__c,
		                                         Data_Scontrino_KPI__c,
		                                         Numero_Scontrino__c,
		                                         SKU__c,
		                                         Nome_Location__c,
		                                         Prezzo_di_listino_formula__c,
		                                         Prezzo_di_vendita_formula__c,
		                                         Product_Image_Reference__c,
		                                         Seller__r.Name,
		                                         Tipo_Vendita__c,
		                                         Transaction__c
		                                         FROM Transaction_Detail__c
		                                         WHERE Gift__c = false
		                                                         AND AccountId__c  =:accId
		                                                                             //AND Product_Image_Reference__c != null
		                                                                             Order By Data_Scontrino__c Desc
		                                                                             LIMIT 5];

		system.System.debug(tDetails);

		return (tDetails.size() > 0) ? tDetails : null;


	}
	@AuraEnabled
	public static List<Transaction_Detail__c> getTransactionDetailsQueryAll(String accId){


		List<Transaction_Detail__c> tDetails =  [SELECT Id,
		                                         Name,
		                                         Importo_sconto_formula__c,
		                                         Sconto_formula__c,
		                                         Data_Scontrino_KPI__c,
		                                         Numero_Scontrino__c,
		                                         SKU__c,
		                                         Nome_Location__c,
		                                         Prezzo_di_listino_formula__c,
		                                         Prezzo_di_vendita_formula__c,
		                                         Product_Image_Reference__c,
		                                         Seller__r.Name,
		                                         Tipo_Vendita__c,
		                                         Transaction__c
		                                         FROM Transaction_Detail__c
		                                         WHERE Gift__c = false
		                                                         AND AccountId__c =:accId
		                                                                            //AND Product_Image_Reference__c != null
		                                                                            Order By Data_Scontrino__c Desc
		];

		system.System.debug(tDetails);

		return (tDetails.size() > 0) ? tDetails : null;


	}
	@AuraEnabled
	public static Integer getTransactionDetailsSize(String accId){


		Integer tDetails =  [SELECT count()
		                     FROM Transaction_Detail__c
		                     WHERE Gift__c = false
		                                     AND AccountId__c =:accId
		];



		return (tDetails != 0) ? tDetails : 0;


	}

}