src/objects/Associated__c.object
<CustomObject>
    <description>Anagrafiche venditori negozi (collegato a Store di riferimento)</description>
    <fields>
        <fullName>Id_Associate_Micros__c</fullName>
        <label>Id Associate Micros</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Associateds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Associate</label>
    <nameField>
        <label>Associate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Anagrafica Store con informazioni legal entity</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/RestAssociatedTest.cls
@isTest
private class RestAssociatedTest {
    
    @isTest static void test_get() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

         Location__c c = new Location__c();
        insert c;


         Associated__c t = new Associated__c();
         t.Id_Associate_Micros__c = '123456789';
         t.Location__c = c.Id;
        insert t;

        req.requestURI =    '/Associated_v1.0/123456789'; 
        req.httpMethod = 'GET';

        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = RestAssociated.doGet();
        
        System.debug(rw);
    }

        @isTest static void test_get1() {
            new RestAssociated.RestAssociatedHandler().beforeUpdate(null, null, null);
            new RestAssociated.RestAssociatedHandler().afterUpdateResponse(null, null, null);
            new RestAssociated.RestAssociatedHandler().beforeInsert(null);
            new RestAssociated.RestAssociatedHandler().afterInsert(null);
        }

    
}