src/objects/Attivita_Marketing__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <errorMessage>The customer doesn&apos;t have marketing consent.</errorMessage>
            <filterItems>
                <field>Account.Privacy_1__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Privacy2__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Privacy1__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gift</relationshipLabel>
        <relationshipName>Attivit_Marketing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dettaglio_Transazione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dettaglio Transazione</label>
        <referenceTo>Transaction_Detail__c</referenceTo>
        <relationshipName>Attivit_Marketing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prodotto</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Attivit_Marketing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Gift</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift</pluralLabel>
    <recordTypes>
        <fullName>Gift_Collection</fullName>
        <active>true</active>
        <label>Gift Collection</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Gift__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gift</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/onTransactionDetailTriggerHandler.cls
public with sharing class onTransactionDetailTriggerHandler {

    public static void CreateGiftActivity(list<Transaction_Detail__c> TransactionDetail){

        list<Attivita_Marketing__c> ListNewActivity = new list<Attivita_Marketing__c>();

        set<string> SetTransactionIds               = new set<string>();
        list<Transaction__c> ListTransaction        = new list<Transaction__c>();
        map<string, string> MapTransactions         = new map<string, string>();
        
        string GiftRecTypeId = [Select id 
                                From Recordtype 
                                Where SobjectType = 'Attivita_Marketing__c' and
                                DeveloperName = 'Gift_Collection'].Id;

        for(Transaction_Detail__c t:TransactionDetail){
        
            if(t.Gift__c){
                
                SetTransactionIds.add(t.Transaction__c);
                
            }
            
        }
            
        ListTransaction = [ Select id, Account__c
                            From Transaction__c
                            Where id IN:SetTransactionIds];
                            
        for(Transaction__c t:ListTransaction){
            MapTransactions.put(t.Id, t.Account__c);
        }

        for(Transaction_Detail__c td:TransactionDetail){
        
            if(td.Gift__c && MapTransactions.containsKey(td.Transaction__c)){
        
                Attivita_Marketing__c am    = new Attivita_Marketing__c();
                am.RecordTypeId             = GiftRecTypeId;
                am.Cliente__c               = MapTransactions.get(td.Transaction__c);
                am.Product__c               = td.Product__c;
                am.Dettaglio_Transazione__c = td.Id;
                am.Data__c                  = system.today();
                am.Gift__c                  = true;
                ListNewActivity.add(am);
        
            }
        
        }

        if(ListNewActivity.size()>0){
            insert ListNewActivity;
        }


    }

}