src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Brand_Specialist</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Brand Specialist</description>
        <label>Brand Specialist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reso_Cambio</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Reso/Cambio</description>
        <label>Reso/Cambio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reso_Cambio_in_Store</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Reso/Cambio in Store</description>
        <label>Reso/Cambio in Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_E_commerce</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Ticket E-commerce</description>
        <label>Ticket E-commerce</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_E_commerce_Notify_Me</fullName>
        <active>true</active>
        <businessProcess>Notify Me</businessProcess>
        <label>Ticket E-commerce – Notify Me</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ticket_OMS</fullName>
        <active>true</active>
        <businessProcess>Ticket E-commerce</businessProcess>
        <description>Ticket OMS</description>
        <label>Ticket OMS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Caso_BrandSpecialist__c</fullName>
        <label>Caso_BrandSpecialist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_CustomerCare__c</fullName>
        <label>Caso_CustomerCare</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_OMS__c</fullName>
        <label>Caso_OMS</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambioStore__c</fullName>
        <label>Caso_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambio__c</fullName>
        <label>Caso_ResoCambio</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_ResoCambioStore__c</fullName>
        <label>Task_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Wishlist__c</fullName>
        <label>Task_Wishlist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Reso_Cambio_in_Store</fullName>
        <active>true</active>
        <description>Reso/Cambio in Store</description>
        <label>Reso/Cambio in Store</label>
    </recordTypes>
    <recordTypes>
        <fullName>Wishlist</fullName>
        <active>true</active>
        <description>Wishlist</description>
        <label>Wishlist</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChatterAnswersEscalationTriggerTest.cls
@isTest
private class ChatterAnswersEscalationTriggerTest {
	static testMethod void validateQuestionEscalation() {
		RecordTypeSetting__c rst = new RecordTypeSetting__c(Name='General');
            rst.Caso_ResoCambio__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio');
            rst.Caso_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Case', 'Reso_Cambio_in_Store');
            rst.Caso_CustomerCare__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce');
            rst.Caso_BrandSpecialist__c = DescribeUtils.getRecordTypeId('Case', 'Brand_Specialist');
            rst.Caso_OMS__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_OMS');
            rst.Task_ResoCambioStore__c = DescribeUtils.getRecordTypeId('Task', 'Reso_Cambio_in_Store');
            rst.Task_Wishlist__c = DescribeUtils.getRecordTypeId('Task', 'Wishlist');
            rst.Caso_NotifyMe__c = DescribeUtils.getRecordTypeId('Case', 'Ticket_E_commerce_Notify_Me');
            insert rst;


		String questionTitle = 'questionTitle';
		String questionBody = 'questionBody';
		Community[] c = [SELECT Id from Community];
		// We cannot create a question without a community
		if (c.size() == 0) { return; }
		String communityId = c[0].Id;

		Case cTest = new Case();
		cTest.Origin = 'Chatter Answers';
		cTest.CommunityId = communityId;
		cTest.Subject = questionTitle;
		cTest.Description = questionBody;
	
		
		Question q = new Question();
		q.Title = questionTitle;
		q.Body = questionBody;
		q.CommunityId = communityId;
		insert(q);
		q.Priority = 'high';
		cTest.QuestionId = q.Id;
		insert cTest;
		update(q);
		Case ca = [SELECT Origin, CommunityId, Subject, Description from Case where QuestionId =: q.Id limit 1];
		// Test that escaltion trigger correctly escalate the question to a case
		System.assertEquals(questionTitle, ca.Subject);
		System.assertEquals(questionBody, ca.Description);
		System.assertEquals('Chatter Answers', ca.Origin);
		System.assertEquals(communityId, ca.CommunityId);
	}
}