src/objects/Credit__c.object
<CustomObject>
    <description>Dettaglio House Account (Xstore) e Store Credit (E-Commerce)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Crediti</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credito</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Credito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crediti</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/classes/RestCreditTest.cls
@isTest
private class RestCreditTest {
    
    @isTest static void test_post() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){

        req.requestURI =    '/Credit_v1.0/'; 
        req.httpMethod = 'POST';
        

        Account customer = new Account();
        customer.LastName = 'Brambilla';
        insert customer;

         Credit__c c = new Credit__c();
        c.Account__c = customer.Id;
        //insert c;
        
        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = RestCredit.doPost(c);
        
        System.debug(rw);
            
        }
        Test.stopTest();
    }

    @isTest static void test_get() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){

         Account customer = new Account();
        customer.LastName = 'Brambilla';
        insert customer;

        Credit__c c = new Credit__c();
        c.Account__c = customer.Id;
        insert c;

        req.requestURI =    '/Credit_v1.0/' + c.Id; 
        req.httpMethod = 'GET';

        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = RestCredit.doGet();
        
        System.debug(rw);
            
        }
        Test.stopTest();
    }

    @isTest static void test_patch() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){

         Account customer = new Account();
        customer.LastName = 'Brambilla';
        insert customer;

        Credit__c c = new Credit__c();
        c.Account__c = customer.Id;
        insert c;

        req.requestURI =    '/Credit_v1.0/' + c.Id; 
        req.httpMethod = 'PATCH';

        RestContext.response= res;
        RestContext.request = req;
        
        ResponseWrapper rw = RestCredit.doPatch(c);
        
        System.debug(rw);
            
        }
        Test.stopTest();
    }

}