src/objects/Mulesoft_Endpoint__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LIMIT__c</fullName>
        <label>LIMIT</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Mulesoft Endpoint</label>
</CustomObject>

src/objects/SV_Log__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Payload__c</fullName>
        <label>Input Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Output_Payload__c</fullName>
        <label>Output Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Attempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retry Attempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SFtoMuleSoft_Retry.cls
public class SFtoMuleSoft_Retry {
    @AuraEnabled
    public static String doRetry(){
        Mulesoft_Endpoint__c mce = Mulesoft_Endpoint__c.getInstance();
        List<SV_Log__c> logList;
        if(mce.LIMIT__c!= null){
            String query= 'SELECT Id, Name, Input_Payload__c, Output_Payload__c, Source__c, Status__c, Success__c,  Retry_Attempt__c,AccountID__c FROM SV_Log__c WHERE Success__c = false AND Retry_Attempt__c = false Order by Source__c LIMIT '+mce.LIMIT__c;
            logList = Database.query(query);
        }else{
            logList = [SELECT Id, Name, Input_Payload__c, Output_Payload__c, Source__c, Status__c, Success__c,  Retry_Attempt__c,AccountID__c
                                    FROM SV_Log__c
                                    WHERE Success__c = false AND Retry_Attempt__c = false
                                    Order by Source__c ];
        }

        
        ID jobID = System.enqueueJob(new SF_to_Mulesoft_Queueable(logList));
        return 'abc';
    }

}