src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProdottiImagesPreviewControllerTest.cls
@isTest
public class ProdottiImagesPreviewControllerTest {
    
    @isTest
    static void validateProdottiImagesPreviewController() {
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        
        
        Test.startTest();
        System.runAs(usr){
            
            Account acc = AllDataFactory.create_Account();
        insert acc;
        
        String parentId = (String)acc.Id;
        
        Product__c prod = AllDataFactory.create_Product();
        insert prod;
        
        Transaction__c trans = AllDataFactory.create_Transactions();
        insert trans;
        
        Transaction_Detail__c detail = AllDataFactory.create_Transaction_Details();
        insert detail;
        
        ContentVersion cv = AllDataFactory.create_ContentVersion();
        insert cv;
        
        ContentDocumentLink cDe = AllDataFactory.create_ContentDocumentLink(cv, detail);
        insert cDe;
            
            List<ProdottiImagesPreviewController.productContainer> stringArray = ProdottiImagesPreviewController.getAttachments(parentId, 'purchase');
        }
        Test.stopTest();
        
    }
}