src/objects/Product__c.object
<CustomObject>
    <description>Catalogo prodotti (SKU)</description>
    <label>Prodotto.</label>
    <nameField>
        <label>Nome Prodotto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prodotti</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codice Articolo</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionDetialListViewControllerTest.cls
@isTest
public class TransactionDetialListViewControllerTest {
    @isTest
    public static void  testMethod1(){
        User usr = AllDataFactory.create_User();
        insert usr;
        
        
        
        
        
        System.runAs(usr){
            
            Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
            Account acc =  AllDataFactory.create_Account();
            insert acc;
            
            Product__c prod = AllDataFactory.create_Product();
            insert prod;
            
            Transaction__c transazione =  AllDataFactory.create_Transactions();
            insert transazione;
            
            Transaction_Detail__c Transaction_Detail =  AllDataFactory.create_Transaction_Details();
            insert Transaction_Detail;
            
            List<Transaction_Detail__c> tDetails =  TransactionDetialListViewController.getTransactionDetailsLimit5(acc.Id);
            List<Transaction_Detail__c> tAllDetails =  TransactionDetialListViewController.getTransactionDetailsQueryAll(acc.Id);
            Integer tDetailsInt =  TransactionDetialListViewController.getTransactionDetailsSize(acc.Id);
        }
        
    }
    
}