src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Tender__c.object
<CustomObject>
    <description>Modalità di pagamento utilizzati nelle transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Tenders</relationshipLabel>
        <relationshipName>Tenders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tender</label>
    <nameField>
        <label>Nome Tender</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WebService_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OMS_Endpoint__c</fullName>
        <label>OMS Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Enviroment__c</fullName>
        <inlineHelpText>INT = Integration test, 
‘blank’ = Production</inlineHelpText>
        <label>OMS Enviroment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Task_Parameter__c</fullName>
        <label>OMS Task Parameter</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenderDetailPostRecordLimit__c</fullName>
        <label>TenderDetailPostRecordLimit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TransactionDetailPostRecordLimit__c</fullName>
        <label>TransactionDetailPostRecordLimit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WebService Settings</label>
</CustomObject>

src/classes/RestMultiTenderTest.cls
@isTest
private class RestMultiTenderTest {
  
    @isTest static void test_post() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
            
            req.requestURI =    '/MultiTender_v1.0/'; 
            req.httpMethod = 'POST';
            
            WebService_Settings__c cs= new WebService_Settings__c(Name='General');
            cs.TenderDetailPostRecordLimit__c = 50;
            cs.TransactionDetailPostRecordLimit__c = 50;
            cs.OMS_Endpoint__c = 'http://46.30.169.234:8084/dispatch/tickets/oms/close';
            cs.OMS_Enviroment__c = '';
            cs.OMS_Task_Parameter__c = 'ticket';
            insert cs;
            
            Account customer = new Account();
            customer.LastName = 'Brambilla';
            insert customer;
            
            Transaction__c c = new Transaction__c();
            c.Account__c = customer.Id;
            insert c;
            
            Tender__c t = new Tender__c();
            t.Transaction__c = c.Id;
            
            Tender__c t1 = new Tender__c();
            t1.Transaction__c = c.Id;
            //insert t;
            
            List<Tender__c> l = new List<Tender__c>{t, t1};
                RestMultiTender.ListWrapper w = new RestMultiTender.ListWrapper(l);
            
            String j = JSON.serialize(w);
            
            RestContext.response= res;
            RestContext.request = req;
            req.requestBody = Blob.valueOf(j);
            
            ResponseWrapper rw = RestMultiTender.doPost();
            
            System.debug(rw);
            
        }
        Test.stopTest();
    }
    
}