src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Listino__c</fullName>
        <label>Prezzo di Listino (Sede)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_Listino__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Vendita__c</fullName>
        <label>Prezzo di Vendita (Sede)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_Vendita__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Prezzo_di_Listino__c</fullName>
        <description>Prezzo di listino espresso nella valuta del negozio comprensivo di VAT</description>
        <label>Prezzo di Listino (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_Vendita__c</fullName>
        <description>Prezzo effettivo pagato dal cliente lordo iva netto tasse- Ricavabile come full price - discount value</description>
        <label>Prezzo di Vendita (Sede)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WebService_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OMS_Endpoint__c</fullName>
        <label>OMS Endpoint</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Enviroment__c</fullName>
        <inlineHelpText>INT = Integration test, 
‘blank’ = Production</inlineHelpText>
        <label>OMS Enviroment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OMS_Task_Parameter__c</fullName>
        <label>OMS Task Parameter</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenderDetailPostRecordLimit__c</fullName>
        <label>TenderDetailPostRecordLimit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TransactionDetailPostRecordLimit__c</fullName>
        <label>TransactionDetailPostRecordLimit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WebService Settings</label>
</CustomObject>

src/classes/RestMultiTransactionDetailTest.cls
@isTest
private class RestMultiTransactionDetailTest {
  
  @isTest static void test_post() {
    RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
      
      User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){

        req.requestURI =    '/MultiTransaction_Detail_v1.0/'; 
        req.httpMethod = 'POST';

        WebService_Settings__c cs= new WebService_Settings__c(Name='General');
        cs.TransactionDetailPostRecordLimit__c = 50;
        cs.TenderDetailPostRecordLimit__c = 50;
        cs.OMS_Endpoint__c = 'http://46.30.169.234:8084/dispatch/tickets/oms/close';
        cs.OMS_Enviroment__c = '';
        cs.OMS_Task_Parameter__c = 'ticket';
        insert cs;

        Account customer = new Account();
        customer.LastName = 'Brambilla';
        insert customer;

        Transaction__c c = new Transaction__c();
        c.Account__c = customer.Id;
        insert c;

         Transaction_Detail__c t = new Transaction_Detail__c();
         t.Transaction__c = c.Id;
         t.CurrencyIsoCode = 'EUR';
         t.Prezzo_di_Vendita__c = 100;
         t.Prezzo_di_Listino__c = 100;

         Transaction_Detail__c t1 = new Transaction_Detail__c();
         t1.Transaction__c = c.Id;
         t1.CurrencyIsoCode = 'EUR';
         t1.Prezzo_di_Vendita__c = 100;
         t1.Prezzo_di_Listino__c = 100;
        //insert t;

        List<Transaction_Detail__c> l = new List<Transaction_Detail__c>{t, t1};
        RestMultiTransactionDetail.ListWrapper lw = new RestMultiTransactionDetail.ListWrapper(l);
        String j = JSON.serialize(lw);

        RestContext.response= res;
        RestContext.request = req;
        req.requestBody = Blob.valueOf(j);
        
        ResponseWrapper rw = RestMultiTransactionDetail.doPost();
        
        System.debug(rw);
            
        }
        Test.stopTest();
  }

}