src/objects/Profile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Profile</label>
</CustomObject>

src/objects/Relazione_Ghost__c.object
<CustomObject>
    <description>Oggetto di sistema creato per gestire trigger di creazione relazione</description>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Relazioni_Ghost</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cliente_in_Relazione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente in Relazione</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Relazioni_Ghost1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legame_Cliente__c</fullName>
        <label>Legame Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legame_Cliente_in_Relazione__c</fullName>
        <label>Legame Cliente in Relazione</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Legame_Cliente__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Relazione Ghost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OnRelazioneGhostTriggerHandlerTest.cls
@isTest
private class OnRelazioneGhostTriggerHandlerTest {

    static testMethod void CreateRelazioniTest() {

    /*        
  	Test for: 
    - OnRelazioneGhostTriggerHandler.CreateRelazioni
    - OnRelazioneGhostTrigger
  	*/      
        User usr = AllDataFactory.create_User();
        insert usr;
        
        Profile__c profileSettings = AllDataFactory.create_TriggerSetting(usr.ProfileId);
        insert profileSettings;
        
        Test.startTest();
        System.runAs(usr){
        
        Account a1  = new Account();
        a1.LastName = 'TestLastName1';
        insert a1;
        
        Account a2	= new Account();
        a2.LastName = 'TestLastName2';
        insert a2;
        
        Relazione_Ghost__c r   				= new Relazione_Ghost__c();
        r.Cliente__c						= a1.Id;
        r.Cliente_in_Relazione__c			= a2.Id;
        r.Legame_Cliente__c					= 'Marito';
        r.Legame_Cliente_in_Relazione__c	= 'Moglie';
        insert r;
            
            }
        Test.stopTest();
             
    }
    
}