src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Caso_BrandSpecialist__c</fullName>
        <label>Caso_BrandSpecialist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_CustomerCare__c</fullName>
        <label>Caso_CustomerCare</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_OMS__c</fullName>
        <label>Caso_OMS</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambioStore__c</fullName>
        <label>Caso_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caso_ResoCambio__c</fullName>
        <label>Caso_ResoCambio</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_ResoCambioStore__c</fullName>
        <label>Task_ResoCambioStore</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Wishlist__c</fullName>
        <label>Task_Wishlist</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/classes/changeOwnerControllerTest.cls
@isTest
public class changeOwnerControllerTest {

    @isTest
    public static void test_changeOwner(){
        String userID = changeOwnerController.fetchUser();

        RecordType caseRt = [SELECT Id,Name 
                                FROM RecordType
                                WHERE sObjectType='Case' AND Name = 'Ticket E-commerce'];
          
                                
        List<RecordType> caseRtOMG = [SELECT Id,Name 
                                    FROM  RecordType WHERE  Name IN ('Brand Specialist', 'Reso/Cambio', 'Reso/Cambio in Store', 'Reso/Cambio in Store', 'Ticket E-commerce', 'Ticket E-commerce – Notify Me', 'Ticket OMS', 'Wishlist')
                                    ORDER BY Name];

        RecordTypeSetting__c rts = new RecordTypeSetting__c(Name = 'General',
                                                            CurrencyIsoCode = 'EUR',
                                                            Caso_BrandSpecialist__c = caseRtOMG[0].Id,
                                                            Caso_ResoCambio__c = caseRtOMG[1].Id,
                                                            Task_ResoCambioStore__c = caseRtOMG[2].Id,
                                                            Caso_ResoCambioStore__c = caseRtOMG[3].Id,
                                                            Caso_CustomerCare__c = caseRtOMG[4].Id,
                                                            Caso_NotifyMe__c = caseRtOMG[5].Id,
                                                            Caso_OMS__c = caseRtOMG[6].Id,
                                                            Task_Wishlist__c = caseRtOMG[7].Id);
        insert rts;
                        


        Test.startTest();
        Case c = new Case();
        c.Status= 'Nuovo';
        c.RecordTypeId =caseRt.Id;
        c.OwnerId =userID;
        insert c;
        
        
        
            changeOwnerController.changeOwner(userID);
        Test.stopTest();
    }
}