src/objects/RecordTypeSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Caso_OMS__c</fullName>
        <label>Caso_OMS</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RecordTypeSetting</label>
</CustomObject>

src/classes/CaseTest.cls
@isTest(seeAllData=true)
private class CaseTest {
    @isTest static void testEchoString() {             
        // This causes a fake response to be generated

        RecordTypeSetting__c rts    = RecordTypeSetting__c.getValues('General');

        Case c = new Case();
        c.subject = 'ad';
        c.Status = 'New';
        c.RecordTypeId = rts.Caso_OMS__c;
        insert c;

        System.debug('After Insert');

        c.Status = 'Closed';
        update c;
        
        Test.setMock(WebServiceMock.class, new WebServiceCloseCaseMockImpl());

        Test.startTest();

        System.debug('After Update');

        OnCaseTriggerHandler.CloseTicketCallout(new List<Case>{c});

        Test.stopTest();
    }
}