src/objects/Relazione_Ghost__c.object
<CustomObject>
    <description>Oggetto di sistema creato per gestire trigger di creazione relazione</description>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Relazioni_Ghost</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cliente_in_Relazione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente in Relazione</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Relazioni_Ghost1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legame_Cliente__c</fullName>
        <label>Legame Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legame_Cliente_in_Relazione__c</fullName>
        <label>Legame Cliente in Relazione</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Legame_Cliente__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Relazione Ghost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relazioni__c.object
<CustomObject>
    <description>Relationships with other customers</description>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relazioni</relationshipLabel>
        <relationshipName>Relazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cliente_in_Relazione__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente in Relazione</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relazioni (Cliente in Relazione)</relationshipLabel>
        <relationshipName>Relazioni1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key_Relazione_Ghost__c</fullName>
        <label>Key Relazione Ghost</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legame__c</fullName>
        <label>Legame</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Legami_Parentela</valueSetName>
        </valueSet>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Relazioni Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OnRelazioneGhostTriggerHandler.cls
public with sharing class OnRelazioneGhostTriggerHandler{

    public static void CreateRelazioni(list<Relazione_Ghost__c> rel){

        list<Relazioni__c> ListRelazioni	= new list<Relazioni__c>();

		String hashString = '1000' + String.valueOf(Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS'));
		Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(hashString));
		String hexDigest = EncodingUtil.convertToHex(hash);
		system.debug('TEN@hexDigest : ' + hexDigest );
        
        for(Relazione_Ghost__c r:rel){
            
			Relazioni__c nr             = new Relazioni__c();
			nr.Cliente__c               = r.Cliente__c;
			nr.Cliente_in_Relazione__c	= r.Cliente_in_Relazione__c;
			nr.Legame__c                = r.Legame_Cliente_in_Relazione__c;
			nr.Key_Relazione_Ghost__c	= hexDigest;
            ListRelazioni.add(nr);
                
            Relazioni__c nri            = new Relazioni__c();
			nri.Cliente__c              = r.Cliente_in_Relazione__c;
			nri.Cliente_in_Relazione__c = r.Cliente__c;
			nri.Legame__c               = r.Legame_Cliente__c;
			nri.Key_Relazione_Ghost__c	= hexDigest;
            ListRelazioni.add(nri);
            
        }        

        if(ListRelazioni.size()>0){      
            insert ListRelazioni;          
        }
           
    }

}