src/objects/Relazioni__c.object
<CustomObject>
    <description>Relationships with other customers</description>
    <fields>
        <fullName>Key_Relazione_Ghost__c</fullName>
        <label>Key Relazione Ghost</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Relazioni Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OnRelazioneTriggerHandlerTest.cls
@isTest
private class OnRelazioneTriggerHandlerTest {

    static testMethod void DeleteRelazioniTest() {

	/*        
  	Test for: 
    - OnRelazioneTriggerHandler.DeleteRelazioni
    - OnRelazioneTrigger
  	*/        
        
        Relazioni__c r1   = new Relazioni__c();
        r1.Key_Relazione_Ghost__c = '0123456789';
        insert r1;
        
        Relazioni__c r2   = new Relazioni__c();
        r2.Key_Relazione_Ghost__c = '0123456789';
        insert r2;
        
		delete r1;
               
    }
    
}