src/objects/Relazioni__c.object
<CustomObject>
    <description>Relationships with other customers</description>
    <fields>
        <fullName>Key_Relazione_Ghost__c</fullName>
        <label>Key Relazione Ghost</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Relazione</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Relazioni Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OnRelazioneTriggerHandler.cls
public with sharing class OnRelazioneTriggerHandler{

    public static void DeleteRelazioni(list<Relazioni__c> rel){

        list<Relazioni__c> ListRelazioni    = new list<Relazioni__c>();
		set<string> RelazioniIds			= new set<string>();
        
        for(Relazioni__c r:rel){           
            RelazioniIds.add(r.Key_Relazione_Ghost__c);          
        }        

        ListRelazioni = [Select Id 
                         from Relazioni__c 
                         where Key_Relazione_Ghost__c IN:RelazioniIds];
              
        if(ListRelazioni.size()>0){      
            delete ListRelazioni;          
        }
          
    }

}