src/objects/RussianWebServerLog__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HttpResponseCode__c</fullName>
        <label>HttpResponseCode</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResubmitNumber__c</fullName>
        <label>ResubmitNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XMLRequest__c</fullName>
        <label>XMLRequest</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>XMLResponse__c</fullName>
        <label>XMLResponse</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>RussianWebServerLog</label>
    <nameField>
        <label>RussianWebServerLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RussianWebServerLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ResubmitRussianWebServiceRequest.cls
global class ResubmitRussianWebServiceRequest implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable {
    global String query;

	global void execute(SchedulableContext ctx) {
        ResubmitRussianWebServiceRequest batch = new ResubmitRussianWebServiceRequest();
        Database.executeBatch(batch);
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
   		return Database.getQueryLocator(query);
	}

    
    global void finish(Database.BatchableContext bc) {
    }
    
    global ResubmitRussianWebServiceRequest() {
    this.query  = 'SELECT CreatedDate,Id,ErrorMessage__c,HttpResponseCode__c,ResubmitNumber__c,Name,Status__c,XMLRequest__c,XMLResponse__c FROM RussianWebServerLog__c WHERE HttpResponseCode__c != 200';

	}
    
    global void execute(Database.BatchableContext bc, List<RussianWebServerLog__c> scope) {

        for (RussianWebServerLog__c log : scope) {
         	RussianWebServer.RussianWebServerXMLInvocation(log);
        }
    }
}