src/objects/Tabelle_di_Sistema__c.object
<CustomObject>
    <fields>
        <fullName>Codice__c</fullName>
        <label>Codice</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motivazioni_di_reso__c</fullName>
        <label>Motivazioni di reso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>La taglia del prodotto non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il prodotto ricevuto è diverso da quello ordinato</fullName>
                </value>
                <value>
                    <fullName>Il colore non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il modello non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il tessuto non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Prodotto difettoso</fullName>
                </value>
                <value>
                    <fullName>La consegna è avvenuta in ritardo</fullName>
                </value>
                <value>
                    <fullName>Sto rendendo un regalo</fullName>
                </value>
                <value>
                    <fullName>Non voglio fornire alcuna motivazione</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tabella di Sistema</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Tabella di Sistems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tabelle di Sistema</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transazioni</relationshipLabel>
        <relationshipName>Transazioni</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <formula>Name &amp;  Id_Location_Micros__c &amp; Codice_Cassa__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stato_reso_cambio_Ecommerce__c</fullName>
        <label>Stato Reso/Cambio Ecommerce</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CREATED</fullName>
                </value>
                <value>
                    <fullName>SHIPPED</fullName>
                </value>
                <value>
                    <fullName>WORK_IN_PROGRESS</fullName>
                </value>
                <value>
                    <fullName>ACCEPTED</fullName>
                </value>
                <value>
                    <fullName>CANCELLED</fullName>
                </value>
                <value>
                    <fullName>SUSPENDED</fullName>
                </value>
                <value>
                    <fullName>REFUSED</fullName>
                </value>
                <value>
                    <fullName>CONCLUDED</fullName>
                </value>
                <value>
                    <fullName>COMPLETED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Detail__c.object
<CustomObject>
    <description>Dettaglio Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>Key__c</fullName>
        <formula>Numero_Scontrino__c &amp; Id_Location_Micros__c &amp; Codice_Cassa__c &amp; Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Motivazione_Reso__c</fullName>
        <label>Motivazione Reso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>La taglia del prodotto non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il prodotto ricevuto è diverso da quello ordinato</fullName>
                </value>
                <value>
                    <fullName>Il colore non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il modello non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Il tessuto non corrisponde alle aspettative</fullName>
                </value>
                <value>
                    <fullName>Prodotto difettoso</fullName>
                </value>
                <value>
                    <fullName>La consegna è avvenuta in ritardo</fullName>
                </value>
                <value>
                    <fullName>Sto rendendo un regalo</fullName>
                </value>
                <value>
                    <fullName>Non voglio fornire alcuna motivazione</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stato_Reso_Cambio_Ecommerce__c</fullName>
        <label>Stato Reso Cambio/Ecommerce</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CREATED</fullName>
                </value>
                <value>
                    <fullName>WORK_IN_PROGRESS</fullName>
                </value>
                <value>
                    <fullName>ACCEPTED</fullName>
                </value>
                <value>
                    <fullName>REFUSED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transazione</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Dettagli Transazione</relationshipLabel>
        <relationshipName>Transaction_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dettaglio Transazione</label>
    <nameField>
        <label>Numero Dettaglio Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dettagli Transazione</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestTransactionDetail.cls
@RestResource(urlMapping='/Transaction_Detail_v1.0/*')
global without sharing class RestTransactionDetail {


	@HttpPost
	global static ResponseWrapper doPost(Transaction_Detail__c dettaglioTransazione) {
		return new RestTransactionDetailHandler().doPostHandler(dettaglioTransazione);
	}

	@HttpGet
	global static ResponseWrapper doGet() {
		return new RestTransactionDetailHandler().doGetHandler(RestContext.request, RestContext.response);
	}

	@HttpPut
	global static ResponseWrapper doPatch(Transaction_Detail__c dettaglioTransazione) {
		return new RestTransactionDetailHandler().doPatchHandler(dettaglioTransazione);
	}

	public static Transaction_Detail__c getTransactionDetailById(String id){
		return (Transaction_Detail__c)GenericDao.getAllFieldsResultById('Transaction_Detail__c', 'Key__c', id);
	}

	public class RestTransactionDetailHandler extends ProvaHandler {
		public Override Object get(RestRequest req,  RestResponse res){
			String reqUri = req.requestURI.substring(1);

			String[] arr = reqUri.split('\\/');
			Integer arrSize = arr.size();
			String service = arr[0];
			String id = arrSize > 1 ? arr[1] : null;
			String relatedResource = arrSize > 2 ? arr[2] : null;
			String idRelatedResource = arrSize > 3 ? arr[3] : null;

			Transaction_Detail__c a = RestTransactionDetail.getTransactionDetailById(id);
			Map<String, Object> m = a == null ? null : a.getPopulatedFieldsAsMap();

			return m;
		}

		public Override SObject beforeUpdate(RestRequest req,  RestResponse res, SObject obj){
			String reqUri = req.requestURI.substring(1);

			String[] arr = reqUri.split('\\/');
			Integer arrSize = arr.size();
			String service = arr[0];
			String id = arrSize > 1 ? arr[1] : null;
			String relatedResource = arrSize > 2 ? arr[2] : null;
			String idRelatedResource = arrSize > 3 ? arr[3] : null;

			List<Transaction_Detail__c> result = [
				Select m.Id
				From Transaction_Detail__c m
				WHERE Id = :id
			];

			if(result != null && !result.isEmpty()) {
				Transaction_Detail__c m = result.get(0);
				obj.id = m.id;

				// TEN@ 2017-10-11
				System.debug('TEN@obj.get(\'Stato_Reso_Cambio_Ecommerce__c\') : ' +
				             obj.get('Stato_Reso_Cambio_Ecommerce__c'));
				System.debug('TEN@obj.get(\'Status__c\') : ' + obj.get('Status__c'));
				if(obj.get('Stato_Reso_Cambio_Ecommerce__c')=='REFUSED' || obj.get('Status__c')=='CANCELLED') {
					System.debug('TEN@ : Ricalcolo currency');
					CurrencyUtils.convertCurrency((Transaction_Detail__c)obj);
				}
				// TEN@ 2017-10-11

				// TEN@ 2017-12-20 (SALESFORCE-81)
				GetDescrizioneFromCodice(obj);
				// TEN@ 2017-12-20 (SALESFORCE-81)



			} else {
				throw new ResourceException(Label.ERR_0002, Label.MSG_DATA_NOT_FOUND + ' - Id');
			}

			return obj;
		}

		public Override ResponseWrapper afterUpdateResponse(RestRequest req,  RestResponse res, SObject obj){
			return null;
		}

		public Override Boolean beforeInsert(SObject obj){
			CurrencyUtils.convertCurrency((Transaction_Detail__c)obj);

			// TEN@ 2017-12-20 (SALESFORCE-81)
			GetDescrizioneFromCodice(obj);
			// TEN@ 2017-12-20 (SALESFORCE-81)

			//PN20190121
			//fillAccount(obj);

			return true;
		}


		public Override SObject afterInsert(SObject obj){
			return obj;
		}

		public Override String getObjectName(){
			return 'dettaglioTransazione';
		}

		//fill account on detail
		//PN20190121
		/*public void fillAccount(SObject obj){
			String transactionId = (String)obj.get('Transaction__c');
			if(transactionId != null && transactionId != '') {
				Transaction__c transazione;
				Account account;
				List<Transaction__c> transactions = [SELECT Id,Account__c FROM Transaction__c WHERE Id = :transactionId];
				if(transactions != null && transactions.size() > 0) {
					transazione = transactions.get(0);
					String accountId = transazione.Account__c;
					if(accountId != null && accountId != '') {
						//obj.put('Account__c',accountId);
					}
				}
			}

		}*/

		// TEN@ 2017-12-20 (SALESFORCE-81)
		public void GetDescrizioneFromCodice(SObject obj){

			list<Tabelle_di_Sistema__c> ListTabella = new list<Tabelle_di_Sistema__c>();

			if( obj.get('Motivazione_Reso__c')!='' ||
			    obj.get('Motivazione_Reso__c')!=null) {

				ListTabella = [ Select Motivazioni_di_Reso__c
				                from Tabelle_di_Sistema__c
				                where Codice__c =:string.valueOf(obj.get('Motivazione_Reso__c'))];

				if(ListTabella.size()==1) {
					obj.put('Motivazione_Reso__c', ListTabella[0].Motivazioni_di_Reso__c);
				}

			}

		}
		// TEN@ 2017-12-20 (SALESFORCE-81)

	}



}