src/objects/Transaction__c.object
<CustomObject>
    <description>Transazioni Xstore / E-Commerce</description>
    <fields>
        <fullName>PSconto_AUD__c</fullName>
        <label>% di Sconto (AUD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PSconto_DKK__c</fullName>
        <label>% di Sconto (DKK)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PSconto_MOP__c</fullName>
        <label>% di Sconto (MOP)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PSconto_RUB__c</fullName>
        <label>% di Sconto (RUB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_listino_AUD__c</fullName>
        <label>Prezzo di listino (AUD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_listino_DKK__c</fullName>
        <label>Prezzo di listino (DKK)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_listino_MOP__c</fullName>
        <label>Prezzo di listino (MOP)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_listino_MOP__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_listino_RUB__c</fullName>
        <label>Prezzo di listino (RUB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_vendita_AUD__c</fullName>
        <label>Prezzo di vendita (AUD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_vendita_DKK__c</fullName>
        <label>Prezzo di vendita (DKK)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_vendita_MOP__c</fullName>
        <label>Prezzo di vendita (MOP)</label>
        <summarizedField>Transaction_Detail__c.Prezzo_di_vendita_MOP__c</summarizedField>
        <summaryForeignKey>Transaction_Detail__c.Transaction__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Prezzo_di_vendita_RUB__c</fullName>
        <label>Prezzo di vendita (RUB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_AUD__c</fullName>
        <label>Sconto (AUD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_DKK__c</fullName>
        <label>Sconto (DKK)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_MOP__c</fullName>
        <label>Sconto (MOP)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sconto_RUB__c</fullName>
        <label>Sconto (RUB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Transazione</label>
    <nameField>
        <label>Numero Transazione</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transazioni</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/onTransactionTriggerHandler.cls
public class onTransactionTriggerHandler {
    
    public static void setScontoInTransactionInsert(List<Transaction__c> TransactionNew){
        System.debug('SET SCONTO IN TRANSACTION ');
        for(Transaction__c trans : TransactionNew){
            
            trans.Sconto_AUD__c  = (trans.Prezzo_di_listino_AUD__c != 0 && trans.Prezzo_di_vendita_AUD__c <= trans.Prezzo_di_listino_AUD__c) ? (trans.Prezzo_di_listino_AUD__c - trans.Prezzo_di_vendita_AUD__c) : 0; 
            trans.PSconto_AUD__c = (trans.Prezzo_di_listino_AUD__c > 0 && trans.Sconto_AUD__c > 0) ? (trans.Sconto_AUD__c / trans.Prezzo_di_listino_AUD__c)*100 : 0;
            
            
            trans.Sconto_DKK__c  = (trans.Prezzo_di_Vendita_DKK__c != 0 && trans.Prezzo_di_Vendita_DKK__c <= trans.Prezzo_di_listino_DKK__c) ? (trans.Prezzo_di_listino_DKK__c - trans.Prezzo_di_Vendita_DKK__c) : 0; 
            trans.PSconto_DKK__c = (trans.Prezzo_di_listino_DKK__c > 0 && trans.Sconto_DKK__c > 0) ? (trans.Sconto_DKK__c / trans.Prezzo_di_listino_DKK__c)*100 : 0;
            
            trans.Sconto_RUB__c  = (trans.Prezzo_di_vendita_RUB__c != 0 && trans.Prezzo_di_vendita_RUB__c <= trans.Prezzo_di_listino_RUB__c) ? (trans.Prezzo_di_listino_RUB__c - trans.Prezzo_di_vendita_RUB__c) : 0; 
            trans.PSconto_RUB__c = (trans.Prezzo_di_listino_RUB__c > 0 && trans.Sconto_RUB__c > 0) ? (trans.Sconto_RUB__c / trans.Prezzo_di_listino_RUB__c)*100 : 0 ;
            
            trans.Sconto_MOP__c  = (trans.Prezzo_di_vendita_MOP__c != 0 && trans.Prezzo_di_vendita_MOP__c <= trans.Prezzo_di_listino_MOP__c) ? (trans.Prezzo_di_listino_MOP__c - trans.Prezzo_di_vendita_MOP__c) : 0; 
            trans.PSconto_MOP__c = (trans.Prezzo_di_listino_MOP__c > 0 && trans.Sconto_MOP__c > 0) ? (trans.Sconto_MOP__c / trans.Prezzo_di_listino_MOP__c)*100 : 0;
            System.debug('SET SCONTO INside TRANSACTION ' + trans.Sconto_MOP__c + ' -Sconto_MOP__c- ');
        }
    }
    
     public static void setScontoInTransactionUpdate(Map<Id,Transaction__c> TransactionNew, Map<Id,Transaction__c> TransactionOld){
        System.debug('SET SCONTO IN TRANSACTION ');
        
        for(Transaction__c trans : TransactionNew.values()){
            if((TransactionNew.get(trans.Id).Prezzo_di_Listino_AUD__c != TransactionOld.get(trans.Id).Prezzo_di_Listino_AUD__c) || (TransactionNew.get(trans.Id).Prezzo_di_vendita_AUD__c != TransactionOld.get(trans.Id).Prezzo_di_vendita_AUD__c)){
                trans.Sconto_AUD__c  = (trans.Prezzo_di_listino_AUD__c != 0 && trans.Prezzo_di_vendita_AUD__c <= trans.Prezzo_di_listino_AUD__c) ? (trans.Prezzo_di_listino_AUD__c - trans.Prezzo_di_vendita_AUD__c) : 0; 
                trans.PSconto_AUD__c = (trans.Prezzo_di_listino_AUD__c > 0 && trans.Sconto_AUD__c > 0) ? (trans.Sconto_AUD__c / trans.Prezzo_di_listino_AUD__c)*100 : 0;
            }
            if((TransactionNew.get(trans.Id).Prezzo_di_listino_DKK__c != TransactionOld.get(trans.Id).Prezzo_di_listino_DKK__c) || (TransactionNew.get(trans.Id).Prezzo_di_Vendita_DKK__c != TransactionOld.get(trans.Id).Prezzo_di_Vendita_DKK__c)){
                trans.Sconto_DKK__c  = (trans.Prezzo_di_listino_DKK__c != 0 && trans.Prezzo_di_Vendita_DKK__c <= trans.Prezzo_di_listino_DKK__c) ? (trans.Prezzo_di_listino_DKK__c - trans.Prezzo_di_Vendita_DKK__c) : 0; 
                trans.PSconto_DKK__c = (trans.Prezzo_di_listino_DKK__c > 0 && trans.Sconto_DKK__c > 0) ? (trans.Sconto_DKK__c / trans.Prezzo_di_listino_DKK__c)*100 : 0;
            }
            if((TransactionNew.get(trans.Id).Prezzo_di_listino_RUB__c != TransactionOld.get(trans.Id).Prezzo_di_listino_RUB__c) || (TransactionNew.get(trans.Id).Prezzo_di_vendita_RUB__c != TransactionOld.get(trans.Id).Prezzo_di_vendita_RUB__c)){
                trans.Sconto_RUB__c  = (trans.Prezzo_di_listino_RUB__c != 0 && trans.Prezzo_di_vendita_RUB__c <= trans.Prezzo_di_listino_RUB__c) ? (trans.Prezzo_di_listino_RUB__c - trans.Prezzo_di_vendita_RUB__c) : 0; 
                trans.PSconto_RUB__c = (trans.Prezzo_di_listino_RUB__c > 0 && trans.Sconto_RUB__c > 0) ? (trans.Sconto_RUB__c / trans.Prezzo_di_listino_RUB__c)*100 : 0 ;
            }
            if((TransactionNew.get(trans.Id).Prezzo_di_listino_MOP__c != TransactionOld.get(trans.Id).Prezzo_di_listino_MOP__c) || (TransactionNew.get(trans.Id).Prezzo_di_vendita_MOP__c != TransactionOld.get(trans.Id).Prezzo_di_vendita_MOP__c)){
                trans.Sconto_MOP__c  = (trans.Prezzo_di_listino_MOP__c != 0 && trans.Prezzo_di_vendita_MOP__c <= trans.Prezzo_di_listino_MOP__c) ? (trans.Prezzo_di_listino_MOP__c - trans.Prezzo_di_vendita_MOP__c) : 0; 
                trans.PSconto_MOP__c = (trans.Prezzo_di_listino_MOP__c > 0 && trans.Sconto_MOP__c > 0) ? (trans.Sconto_MOP__c / trans.Prezzo_di_listino_MOP__c)*100 : 0;
            }
        }
    }

}